package com.hnp.backendofflinefirst.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * A reference document attached to a log-sheet template — a procedure, a diagram, a safety note
 * — that operators can open from any log sheet generated by that template.
 *
 * <p><b>Groundwork only.</b> Nothing writes this table yet; it exists so the schema is settled
 * before the upload path, the panel screen and the mobile viewer are built. When that work
 * starts, note two decisions already encoded here:
 *
 * <ul>
 *   <li><b>It hangs off the template, not the sheet.</b> A guide describes how to do the round,
 *       so it belongs to the recurring definition. Per-sheet copies would mean re-uploading the
 *       same PDF for every occurrence.</li>
 *   <li><b>Guides resolve live, unlike {@code field_definitions_snapshot}.</b> Correcting a
 *       procedure should reach sheets already in progress — that is what a procedure is for. If
 *       a requirement ever needs "the guide as it stood when this sheet was raised", freeze it
 *       deliberately rather than assuming the current behaviour was an oversight.</li>
 * </ul>
 *
 * <p>Storage mirrors {@link Attachment}: bytes on disk, metadata here, {@code storageKey} as the
 * indirection that would let object storage replace the filesystem later. The attachment orphan
 * sweep does <em>not</em> cover the guide directory — extend it when uploads are built.
 */
@Entity
@Table(name = "log_sheet_template_guides")
@Getter
@Setter
public class LogSheetTemplateGuide {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "template_id", nullable = false)
    private Long templateId;

    /** Operator-facing name, e.g. «دستورالعمل بازدید پمپ». */
    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "description")
    private String description;

    /** Original upload name, kept so a download offers something recognisable. */
    @Column(name = "file_name", nullable = false)
    private String fileName;

    @Column(name = "mime_type", nullable = false)
    private String mimeType;

    @Column(name = "size_bytes", nullable = false)
    private Long sizeBytes;

    @Column(name = "sha256")
    private String sha256;

    @Column(name = "storage_key", nullable = false)
    private String storageKey;

    @Column(name = "sort_order", nullable = false)
    private Integer sortOrder = 0;

    /**
     * Soft switch rather than a delete: hiding a superseded revision must not destroy the record
     * of what operators were told to follow at the time.
     */
    @Column(name = "active", nullable = false)
    private boolean active = true;

    @Column(name = "uploaded_at", nullable = false)
    private Long uploadedAt;

    @Column(name = "created_by_user_id")
    private Long createdByUserId;
}
