package com.hnp.backendofflinefirst.domain;

/**
 * Used both as a template's generation strategy and as a log sheet's origin.
 * <pre>
 * MANUAL    — created on demand by a user (admin/supervisor)
 * SCHEDULED — auto-generated by the scheduler from a recurring template
 * </pre>
 */
public enum GenerationMode {
    MANUAL,
    SCHEDULED
}
