-- =============================================================================
-- backend-offline-first — consolidated schema (V1)
-- Includes: master data, operational data, users/org structure, RBAC permissions,
--           log-sheet lifecycle (generation, assignment, completion, audit),
--           mobile bootstrap + per-log-sheet bundle API.
-- Identifiers: every PK is an auto-incrementing BIGINT (GENERATED BY DEFAULT AS
--              IDENTITY). Business/natural keys (code, local_id, nfc_tag_id,
--              client_action_id, username) stay VARCHAR.
-- Permission model: one row per HTTP endpoint, code = METHOD:path
-- =============================================================================

-- =============================================================================
-- users
-- Application users for admin panel login and field operations.
-- =============================================================================
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    BIGINT,
    updated_at    BIGINT,
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- =============================================================================
-- operational_units
-- Hierarchical operational units (org structure). Each unit may have sub-units.
-- Used to scope log-sheet visibility for unit-scoped roles.
-- =============================================================================
CREATE TABLE operational_units (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(255),
    name       VARCHAR(255),
    parent_id  BIGINT,
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- unit_supervisors / unit_operators
-- Many-to-many links between operational units and supervising/operator users.
-- =============================================================================
CREATE TABLE unit_supervisors (
    unit_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (unit_id, user_id)
);

CREATE TABLE unit_operators (
    unit_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (unit_id, user_id)
);

-- =============================================================================
-- permissions
-- Atomic access rights: one row per HTTP endpoint (code = METHOD:path).
-- Assigned to roles via role_permissions; checked by Spring Security @PreAuthorize.
-- =============================================================================
CREATE TABLE permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(255) NOT NULL,
    name          VARCHAR(255),
    category      VARCHAR(255),
    http_method   VARCHAR(10),
    endpoint_path VARCHAR(512),
    CONSTRAINT uk_permissions_code UNIQUE (code)
);

-- =============================================================================
-- roles
-- Named permission groups. system_role=true roles are protected from deletion.
-- =============================================================================
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    system_role BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  BIGINT,
    updated_at  BIGINT,
    CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- =============================================================================
-- app_settings
-- Key/value application configuration (e.g. excel export limits).
-- =============================================================================
CREATE TABLE app_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    value       VARCHAR(500) NOT NULL,
    updated_at  BIGINT
);

INSERT INTO app_settings (setting_key, value, updated_at) VALUES
('excel.export.max_rows', '10000', 0),
('audit.retention.days', '90', 0),
('auth.jwt.expiry_minutes', '480', 0);

-- =============================================================================
-- locations
-- Hierarchical site/area master data. Each location belongs to one operational unit.
-- =============================================================================
CREATE TABLE locations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(255),
    name       VARCHAR(255),
    parent_id  BIGINT,
    unit_id    BIGINT,
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- plant_systems
-- Physical or logical plant systems within a location.
-- =============================================================================
CREATE TABLE plant_systems (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255),
    name        VARCHAR(255),
    parent_id   BIGINT,
    location_id BIGINT,
    created_at  BIGINT,
    updated_at  BIGINT
);

-- =============================================================================
-- main_functions
-- Top-level functional groupings under a plant system or directly under a location.
-- =============================================================================
CREATE TABLE main_functions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255),
    name        VARCHAR(255),
    system_id   BIGINT,
    location_id BIGINT,
    created_at  BIGINT,
    updated_at  BIGINT
);

-- =============================================================================
-- sub_functions
-- Granular functions/equipment groups under a main function, system or location.
-- =============================================================================
CREATE TABLE sub_functions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(255),
    name             VARCHAR(255),
    tag              VARCHAR(255),
    main_function_id BIGINT,
    system_id        BIGINT,
    location_id      BIGINT,
    created_at       BIGINT,
    updated_at       BIGINT
);

-- =============================================================================
-- asset_classes / field_definitions
-- Asset type definitions and dynamic form field schema per class.
-- =============================================================================
CREATE TABLE asset_classes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    fields     JSONB,
    created_at BIGINT,
    updated_at BIGINT
);

CREATE TABLE field_definitions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id   BIGINT,
    field_key  VARCHAR(255),
    label      VARCHAR(255),
    data_type  VARCHAR(255),
    unit       VARCHAR(255),
    required   BOOLEAN      NOT NULL,
    validation JSONB,
    sort_order INTEGER,
    version    INTEGER,
    deleted    BOOLEAN      NOT NULL,
    synced     BOOLEAN      NOT NULL,
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- asset_entries
-- Physical assets tagged with NFC; resolved via GET /api/asset-entries/nfc/{nfcTagId}.
-- =============================================================================
CREATE TABLE asset_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code      VARCHAR(255),
    nfc_tag_id      VARCHAR(255),
    class_id        BIGINT,
    asset_name      VARCHAR(255),
    sub_function_id BIGINT,
    description     VARCHAR(500),
    created_at      BIGINT,
    updated_at      BIGINT,
    CONSTRAINT uk_asset_entries_asset_code UNIQUE (asset_code),
    CONSTRAINT uk_asset_entries_nfc_tag_id UNIQUE (nfc_tag_id)
);

-- =============================================================================
-- data_records
-- Operator inspection records submitted from the offline mobile app.
-- Upserted in batch via POST /api/records/batch using local_id (client key).
-- =============================================================================
CREATE TABLE data_records (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id       VARCHAR(255),
    nfc_tag_id     VARCHAR(255),
    asset_entry_id BIGINT,
    asset_name     VARCHAR(255),
    asset_type_id  BIGINT,
    record_status  VARCHAR(255),
    sync_status    VARCHAR(255),
    form_data      JSONB,
    notes          VARCHAR(255),
    operator_name  VARCHAR(255),
    location       VARCHAR(255),
    synced_at      BIGINT,
    sync_error     VARCHAR(255),
    created_at     BIGINT,
    updated_at     BIGINT,
    CONSTRAINT uk_data_records_local_id UNIQUE (local_id)
);

-- =============================================================================
-- log_sheet_templates
-- Reusable templates for round log-sheet inspections.
-- =============================================================================
CREATE TABLE log_sheet_templates (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255),
    description               VARCHAR(255),
    scope_type                VARCHAR(255),
    scope_id                  BIGINT,
    class_id                  BIGINT,
    operational_unit_id       BIGINT,
    generation_mode           VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    recurrence_unit           VARCHAR(20),
    recurrence_every          INTEGER,
    schedule_start_at         BIGINT,
    schedule_active           BOOLEAN      NOT NULL DEFAULT FALSE,
    next_run_at               BIGINT,
    last_run_at               BIGINT,
    completion_window_minutes INTEGER,
    active                    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                BIGINT,
    updated_at                BIGINT
);

-- =============================================================================
-- log_sheets / log_sheet_entries
-- A log sheet is a unit of work generated (manually or on schedule) from a
-- template, living through a server-authoritative lifecycle. completed_at is
-- device-authoritative (recorded offline, synced later); synced_at is server time.
-- =============================================================================
CREATE TABLE log_sheets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id            VARCHAR(255),
    template_id         BIGINT,
    template_name       VARCHAR(255),
    scope_summary       VARCHAR(255),
    operational_unit_id BIGINT,
    status              VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    origin              VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    assignee_user_id    BIGINT,
    assignment_type     VARCHAR(30),
    assigned_by_user_id BIGINT,
    completed_by_user_id BIGINT,
    operator_name       VARCHAR(255),
    due_at              BIGINT,
    assigned_at         BIGINT,
    claimed_at          BIGINT,
    started_at          BIGINT,
    completed_at        BIGINT,
    expired_at          BIGINT,
    submitted_at        BIGINT,
    synced_at           BIGINT,
    draft_saved_at      BIGINT,
    sync_status         VARCHAR(255),
    sync_error          VARCHAR(255),
    created_at          BIGINT,
    updated_at          BIGINT,
    CONSTRAINT uk_log_sheets_local_id UNIQUE (local_id)
);

CREATE TABLE log_sheet_entries (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id       BIGINT,
    asset_id           BIGINT,
    asset_name         VARCHAR(255),
    nfc_tag_id         VARCHAR(255),
    sub_function_code  VARCHAR(255),
    sub_function_tag   VARCHAR(255),
    class_id           BIGINT,
    form_data          JSONB
);

-- =============================================================================
-- log_sheet_action_log
-- Immutable audit trail: every lifecycle action with exact timing.
-- action_at = device/real time; recorded_at = server persist time.
-- client_action_id = idempotency key for offline actions replayed on sync.
-- =============================================================================
CREATE TABLE log_sheet_action_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id     BIGINT       NOT NULL,
    action           VARCHAR(30)  NOT NULL,
    actor_user_id    BIGINT,
    from_user_id     BIGINT,
    to_user_id       BIGINT,
    source           VARCHAR(20),
    action_at        BIGINT       NOT NULL,
    recorded_at      BIGINT       NOT NULL,
    client_action_id VARCHAR(255),
    CONSTRAINT uk_lsal_client_action_id UNIQUE (client_action_id)
);

-- =============================================================================
-- log_sheet_void_submissions
-- Late/offline operator submissions that arrived after someone else already
-- completed the sheet (e.g. a supervisor takeover). Kept for the record but
-- flagged void — never overwrites the authoritative completed sheet.
-- =============================================================================
CREATE TABLE log_sheet_void_submissions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id         BIGINT NOT NULL,
    submitted_by_user_id BIGINT,
    completed_at         BIGINT,
    synced_at            BIGINT,
    reason               VARCHAR(255),
    payload              JSONB
);

-- =============================================================================
-- audit_log
-- Generic field-level change history for master/operational entities.
-- Written asynchronously; changes stored as JSONB [{field, oldValue, newValue}].
-- =============================================================================
CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     VARCHAR(100) NOT NULL,
    entity_id       VARCHAR(255),
    action          VARCHAR(20)  NOT NULL,
    actor_user_id   BIGINT,
    actor_username  VARCHAR(255),
    source          VARCHAR(20),
    request_id      VARCHAR(64),
    changes         JSONB,
    recorded_at     BIGINT       NOT NULL
);

-- =============================================================================
-- Foreign keys — ON DELETE RESTRICT blocks removing a parent while dependents exist.
-- =============================================================================
ALTER TABLE operational_units
    ADD CONSTRAINT fk_operational_units_parent
        FOREIGN KEY (parent_id) REFERENCES operational_units (id) ON DELETE RESTRICT;

ALTER TABLE unit_supervisors
    ADD CONSTRAINT fk_unit_supervisors_unit
        FOREIGN KEY (unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_unit_supervisors_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE unit_operators
    ADD CONSTRAINT fk_unit_operators_unit
        FOREIGN KEY (unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_unit_operators_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE RESTRICT;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT;

ALTER TABLE locations
    ADD CONSTRAINT fk_locations_unit
        FOREIGN KEY (unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_locations_parent
        FOREIGN KEY (parent_id) REFERENCES locations (id) ON DELETE RESTRICT;

ALTER TABLE plant_systems
    ADD CONSTRAINT fk_plant_systems_parent
        FOREIGN KEY (parent_id) REFERENCES plant_systems (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_plant_systems_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT;

ALTER TABLE main_functions
    ADD CONSTRAINT fk_main_functions_system
        FOREIGN KEY (system_id) REFERENCES plant_systems (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_main_functions_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT;

ALTER TABLE sub_functions
    ADD CONSTRAINT fk_sub_functions_main_function
        FOREIGN KEY (main_function_id) REFERENCES main_functions (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_sub_functions_system
        FOREIGN KEY (system_id) REFERENCES plant_systems (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_sub_functions_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT;

ALTER TABLE field_definitions
    ADD CONSTRAINT fk_field_definitions_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT;

ALTER TABLE asset_entries
    ADD CONSTRAINT fk_asset_entries_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_asset_entries_sub_function
        FOREIGN KEY (sub_function_id) REFERENCES sub_functions (id) ON DELETE RESTRICT;

ALTER TABLE data_records
    ADD CONSTRAINT fk_data_records_asset_entry
        FOREIGN KEY (asset_entry_id) REFERENCES asset_entries (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_templates
    ADD CONSTRAINT fk_log_sheet_templates_unit
        FOREIGN KEY (operational_unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheet_templates_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT;

ALTER TABLE log_sheets
    ADD CONSTRAINT fk_log_sheets_template
        FOREIGN KEY (template_id) REFERENCES log_sheet_templates (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheets_unit
        FOREIGN KEY (operational_unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_entries
    ADD CONSTRAINT fk_log_sheet_entries_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_log_sheet_entries_asset
        FOREIGN KEY (asset_id) REFERENCES asset_entries (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheet_entries_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_action_log
    ADD CONSTRAINT fk_lsal_log_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE;

ALTER TABLE log_sheet_void_submissions
    ADD CONSTRAINT fk_lsvs_log_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE;

-- =============================================================================
-- Indexes — sync deltas, lookups, RBAC joins
-- =============================================================================
CREATE INDEX idx_locations_updated_at ON locations (updated_at);
CREATE INDEX idx_plant_systems_updated_at ON plant_systems (updated_at);
CREATE INDEX idx_plant_systems_parent_id ON plant_systems (parent_id);
CREATE INDEX idx_main_functions_updated_at ON main_functions (updated_at);
CREATE INDEX idx_sub_functions_updated_at ON sub_functions (updated_at);
CREATE INDEX idx_asset_classes_updated_at ON asset_classes (updated_at);
CREATE INDEX idx_field_definitions_updated_at ON field_definitions (updated_at);
CREATE INDEX idx_asset_entries_updated_at ON asset_entries (updated_at);
CREATE INDEX idx_log_sheet_templates_updated_at ON log_sheet_templates (updated_at);
CREATE INDEX idx_field_definitions_class_id ON field_definitions (class_id);
CREATE INDEX idx_log_sheet_entries_log_sheet_id ON log_sheet_entries (log_sheet_id);
CREATE INDEX idx_operational_units_updated_at ON operational_units (updated_at);
CREATE INDEX idx_operational_units_parent_id ON operational_units (parent_id);
CREATE INDEX idx_locations_unit_id ON locations (unit_id);
CREATE INDEX idx_unit_supervisors_user_id ON unit_supervisors (user_id);
CREATE INDEX idx_unit_operators_user_id ON unit_operators (user_id);
CREATE INDEX idx_log_sheets_operational_unit_id ON log_sheets (operational_unit_id);
CREATE INDEX idx_log_sheets_assignee_user_id ON log_sheets (assignee_user_id);
CREATE INDEX idx_log_sheets_status ON log_sheets (status);
CREATE INDEX idx_log_sheets_due_at ON log_sheets (due_at);
CREATE INDEX idx_log_sheet_templates_next_run_at ON log_sheet_templates (next_run_at);
CREATE INDEX idx_log_sheet_templates_operational_unit_id ON log_sheet_templates (operational_unit_id);
CREATE INDEX idx_audit_log_recorded_at ON audit_log (recorded_at DESC);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_lsal_log_sheet_id ON log_sheet_action_log (log_sheet_id);
CREATE INDEX idx_lsvs_log_sheet_id ON log_sheet_void_submissions (log_sheet_id);
CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);

-- =============================================================================
-- Permissions seed — one row per HTTP endpoint (METHOD:path).
-- IDs are auto-assigned; role_permissions joins by permission code / role code.
-- =============================================================================
INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
-- General
('GET:/', 'داشبورد', 'general', 'GET', '/'),
-- Users
('GET:/users', 'لیست کاربران', 'admin', 'GET', '/users'),
('POST:/users', 'ایجاد کاربر', 'admin', 'POST', '/users'),
('POST:/users/{id}', 'ویرایش کاربر', 'admin', 'POST', '/users/{id}'),
('POST:/users/{id}/change-password', 'تغییر رمز کاربر', 'admin', 'POST', '/users/{id}/change-password'),
('POST:/users/{id}/delete', 'حذف کاربر', 'admin', 'POST', '/users/{id}/delete'),
('POST:/users/import', 'ورود کاربر از اکسل', 'admin', 'POST', '/users/import'),
('GET:/users/import-template', 'دانلود قالب اکسل کاربر', 'admin', 'GET', '/users/import-template'),
-- Roles
('GET:/roles', 'لیست نقش‌ها', 'admin', 'GET', '/roles'),
('POST:/roles', 'ایجاد نقش', 'admin', 'POST', '/roles'),
('POST:/roles/{id}', 'ویرایش نقش', 'admin', 'POST', '/roles/{id}'),
('POST:/roles/{id}/delete', 'حذف نقش', 'admin', 'POST', '/roles/{id}/delete'),
-- Settings
('GET:/settings', 'تنظیمات برنامه', 'admin', 'GET', '/settings'),
('POST:/settings', 'ذخیره تنظیمات برنامه', 'admin', 'POST', '/settings'),
('POST:/settings/audit-retention/run', 'اجرای پاکسازی audit', 'admin', 'POST', '/settings/audit-retention/run'),
('POST:/settings/audit-retention/cancel', 'توقف پاکسازی audit', 'admin', 'POST', '/settings/audit-retention/cancel'),
('GET:/audit-logs', 'مشاهده تاریخچه تغییرات', 'admin', 'GET', '/audit-logs'),
-- Operational units
('GET:/operational-units', 'لیست واحدهای عملیاتی', 'organization', 'GET', '/operational-units'),
('POST:/operational-units', 'ایجاد واحد عملیاتی', 'organization', 'POST', '/operational-units'),
('POST:/operational-units/{id}', 'ویرایش واحد عملیاتی', 'organization', 'POST', '/operational-units/{id}'),
('POST:/operational-units/{id}/delete', 'حذف واحد عملیاتی', 'organization', 'POST', '/operational-units/{id}/delete'),
('POST:/operational-units/import', 'ورود واحد عملیاتی از اکسل', 'organization', 'POST', '/operational-units/import'),
('GET:/operational-units/import-template', 'دانلود قالب اکسل واحد عملیاتی', 'organization', 'GET', '/operational-units/import-template'),
('POST:/operational-units/import-staff', 'ورود سرپرست/اپراتور واحد از اکسل', 'organization', 'POST', '/operational-units/import-staff'),
('GET:/operational-units/import-staff-template', 'دانلود قالب اکسل سرپرست/اپراتور', 'organization', 'GET', '/operational-units/import-staff-template'),
-- Locations
('GET:/locations', 'لیست مکان‌ها', 'master-data', 'GET', '/locations'),
('POST:/locations', 'ایجاد مکان', 'master-data', 'POST', '/locations'),
('POST:/locations/{id}', 'ویرایش مکان', 'master-data', 'POST', '/locations/{id}'),
('POST:/locations/{id}/delete', 'حذف مکان', 'master-data', 'POST', '/locations/{id}/delete'),
('POST:/locations/import', 'ورود مکان از اکسل', 'master-data', 'POST', '/locations/import'),
('GET:/locations/import-template', 'دانلود قالب اکسل مکان', 'master-data', 'GET', '/locations/import-template'),
-- Plant systems
('GET:/plant-systems', 'لیست سیستم‌های واحد', 'master-data', 'GET', '/plant-systems'),
('POST:/plant-systems', 'ایجاد سیستم واحد', 'master-data', 'POST', '/plant-systems'),
('POST:/plant-systems/{id}', 'ویرایش سیستم واحد', 'master-data', 'POST', '/plant-systems/{id}'),
('POST:/plant-systems/{id}/delete', 'حذف سیستم واحد', 'master-data', 'POST', '/plant-systems/{id}/delete'),
('POST:/plant-systems/import', 'ورود سیستم واحد از اکسل', 'master-data', 'POST', '/plant-systems/import'),
('GET:/plant-systems/import-template', 'دانلود قالب اکسل سیستم واحد', 'master-data', 'GET', '/plant-systems/import-template'),
-- Main functions
('GET:/main-functions', 'لیست توابع اصلی', 'master-data', 'GET', '/main-functions'),
('POST:/main-functions', 'ایجاد تابع اصلی', 'master-data', 'POST', '/main-functions'),
('POST:/main-functions/{id}', 'ویرایش تابع اصلی', 'master-data', 'POST', '/main-functions/{id}'),
('POST:/main-functions/{id}/delete', 'حذف تابع اصلی', 'master-data', 'POST', '/main-functions/{id}/delete'),
('POST:/main-functions/import', 'ورود تابع اصلی از اکسل', 'master-data', 'POST', '/main-functions/import'),
('GET:/main-functions/import-template', 'دانلود قالب اکسل تابع اصلی', 'master-data', 'GET', '/main-functions/import-template'),
-- Sub functions
('GET:/sub-functions', 'لیست توابع فرعی', 'master-data', 'GET', '/sub-functions'),
('POST:/sub-functions', 'ایجاد تابع فرعی', 'master-data', 'POST', '/sub-functions'),
('POST:/sub-functions/{id}', 'ویرایش تابع فرعی', 'master-data', 'POST', '/sub-functions/{id}'),
('POST:/sub-functions/{id}/delete', 'حذف تابع فرعی', 'master-data', 'POST', '/sub-functions/{id}/delete'),
('POST:/sub-functions/import', 'ورود تابع فرعی از اکسل', 'master-data', 'POST', '/sub-functions/import'),
('GET:/sub-functions/import-template', 'دانلود قالب اکسل تابع فرعی', 'master-data', 'GET', '/sub-functions/import-template'),
-- Asset classes
('GET:/asset-classes', 'لیست کلاس‌های دارایی', 'master-data', 'GET', '/asset-classes'),
('POST:/asset-classes', 'ایجاد کلاس دارایی', 'master-data', 'POST', '/asset-classes'),
('POST:/asset-classes/{id}', 'ویرایش کلاس دارایی', 'master-data', 'POST', '/asset-classes/{id}'),
('POST:/asset-classes/{id}/delete', 'حذف کلاس دارایی', 'master-data', 'POST', '/asset-classes/{id}/delete'),
('GET:/asset-classes/{classId}/fields', 'لیست فیلدهای کلاس', 'master-data', 'GET', '/asset-classes/{classId}/fields'),
('POST:/asset-classes/{classId}/fields', 'افزودن فیلد به کلاس', 'master-data', 'POST', '/asset-classes/{classId}/fields'),
('POST:/asset-classes/{classId}/fields/{fieldId}', 'ویرایش فیلد کلاس', 'master-data', 'POST', '/asset-classes/{classId}/fields/{fieldId}'),
('POST:/asset-classes/{classId}/fields/{fieldId}/delete', 'حذف فیلد کلاس', 'master-data', 'POST', '/asset-classes/{classId}/fields/{fieldId}/delete'),
-- Asset entries
('GET:/asset-entries', 'لیست دارایی‌ها', 'master-data', 'GET', '/asset-entries'),
('POST:/asset-entries', 'ایجاد دارایی', 'master-data', 'POST', '/asset-entries'),
('POST:/asset-entries/{id}', 'ویرایش دارایی', 'master-data', 'POST', '/asset-entries/{id}'),
('POST:/asset-entries/{id}/delete', 'حذف دارایی', 'master-data', 'POST', '/asset-entries/{id}/delete'),
('POST:/asset-entries/import', 'ورود دارایی از اکسل', 'master-data', 'POST', '/asset-entries/import'),
('GET:/asset-entries/import-template', 'دانلود قالب اکسل دارایی', 'master-data', 'GET', '/asset-entries/import-template'),
-- Log sheet templates
('GET:/log-sheet-templates', 'لیست قالب‌های لاگ', 'master-data', 'GET', '/log-sheet-templates'),
('POST:/log-sheet-templates', 'ایجاد قالب لاگ', 'master-data', 'POST', '/log-sheet-templates'),
('POST:/log-sheet-templates/{id}', 'ویرایش قالب لاگ', 'master-data', 'POST', '/log-sheet-templates/{id}'),
('POST:/log-sheet-templates/{id}/delete', 'حذف قالب لاگ', 'master-data', 'POST', '/log-sheet-templates/{id}/delete'),
-- Operational data
('GET:/records', 'لیست رکوردها', 'operational', 'GET', '/records'),
('GET:/records/{id}', 'جزئیات رکورد', 'operational', 'GET', '/records/{id}'),
('GET:/log-sheets', 'لیست لاگ‌شیت‌ها', 'operational', 'GET', '/log-sheets'),
('GET:/log-sheets/{id}', 'جزئیات لاگ‌شیت', 'operational', 'GET', '/log-sheets/{id}'),
('POST:/log-sheets/generate', 'تولید دستی لاگ‌شیت از قالب', 'operational', 'POST', '/log-sheets/generate'),
('POST:/log-sheets/{id}/claim', 'پیک‌آپ لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/claim'),
('POST:/log-sheets/{id}/release', 'برگرداندن لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/release'),
('POST:/log-sheets/{id}/assign', 'انتساب لاگ‌شیت به اپراتور', 'operational', 'POST', '/log-sheets/{id}/assign'),
('POST:/log-sheets/{id}/reassign', 'بازانتساب لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/reassign'),
('POST:/log-sheets/{id}/extend', 'تمدید مهلت لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/extend'),
('POST:/log-sheets/{id}/takeover', 'تصاحب لاگ‌شیت توسط سرپرست', 'operational', 'POST', '/log-sheets/{id}/takeover'),
('GET:/log-sheets/{id}/fill', 'فرم تکمیل لاگ‌شیت (وب)', 'operational', 'GET', '/log-sheets/{id}/fill'),
('POST:/log-sheets/{id}/complete', 'تکمیل لاگ‌شیت در وب', 'operational', 'POST', '/log-sheets/{id}/complete'),
('GET:/my-inbox', 'کارتابل من', 'operational', 'GET', '/my-inbox'),
('GET:/reports', 'گزارش‌گیری', 'reports', 'GET', '/reports'),
-- Mobile API
('GET:/api/master-data', 'API — دریافت داده پایه', 'api', 'GET', '/api/master-data'),
('POST:/api/records/batch', 'API — ارسال رکورد', 'api', 'POST', '/api/records/batch'),
('POST:/api/log-sheets/batch', 'API — ارسال/تکمیل لاگ‌شیت', 'api', 'POST', '/api/log-sheets/batch'),
('GET:/api/log-sheets/inbox', 'API — کارتابل لاگ‌شیت', 'api', 'GET', '/api/log-sheets/inbox'),
('POST:/api/log-sheets/{id}/claim', 'API — پیک‌آپ لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/claim'),
('POST:/api/log-sheets/{id}/release', 'API — برگرداندن لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/release'),
('POST:/api/log-sheets/{id}/assign', 'API — انتساب لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/assign'),
('POST:/api/log-sheets/{id}/reassign', 'API — بازانتساب لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/reassign'),
('GET:/api/operational-units/{unitId}/operators', 'API — اپراتورهای واحد', 'api', 'GET', '/api/operational-units/{unitId}/operators'),
('GET:/api/asset-entries/nfc/{nfcTagId}', 'API — جستجوی NFC', 'api', 'GET', '/api/asset-entries/nfc/{nfcTagId}'),
('GET:/api/bootstrap', 'API — bootstrap اپ موبایل', 'api', 'GET', '/api/bootstrap'),
('GET:/api/log-sheets/{id}/bundle', 'API — بسته لاگ‌شیت', 'api', 'GET', '/api/log-sheets/{id}/bundle');

-- =============================================================================
-- Default system roles (5)
-- ADMIN            — full access to everything.
-- HIGH_USER          — everything except the admin category (users, roles, settings).
-- SUPERVISOR         — unit-scoped: sees/manages only their own units and sub-units;
--                      may generate, assign/reassign, extend, takeover and complete work;
--                      may create log-sheet templates but not edit/delete them.
-- SENIOR_OPERATOR    — like OPERATOR but may also complete assigned work in the web UI.
-- OPERATOR           — unit-scoped: claim/release and complete work via mobile app only.
-- Supervisor-only actions are additionally gated by an is-supervisor-of-unit
-- relationship check in the service layer.
-- =============================================================================
INSERT INTO roles (code, name, description, system_role, created_at, updated_at) VALUES
('ADMIN',            'مدیر سیستم',    'دسترسی کامل به همه بخش‌ها',                        TRUE, 0, 0),
('HIGH_USER',        'کاربر ارشد',    'همه دسترسی‌ها به‌جز مدیریت کاربران و تنظیمات',       TRUE, 0, 0),
('SUPERVISOR',       'سرپرست',        'مدیریت کارها فقط در واحدهای تحت سرپرستی خود',        TRUE, 0, 0),
('SENIOR_OPERATOR',  'اپراتور ارشد',  'مثل اپراتور؛ تکمیل در وب و اپ موبایل',               TRUE, 0, 0),
('OPERATOR',         'اپراتور',       'پیک‌آپ و تکمیل لاگ‌شیت در اپ موبایل',                TRUE, 0, 0);

-- ADMIN → every permission
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ADMIN';

-- HIGH_USER → everything except admin category
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'HIGH_USER' AND p.category <> 'admin';

-- SUPERVISOR → full log-sheet lifecycle (supervisor actions gated by relationship)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SUPERVISOR' AND p.code IN (
    'GET:/log-sheets',
    'GET:/log-sheets/{id}',
    'POST:/log-sheets/generate',
    'POST:/log-sheets/{id}/claim',
    'POST:/log-sheets/{id}/release',
    'POST:/log-sheets/{id}/assign',
    'POST:/log-sheets/{id}/reassign',
    'POST:/log-sheets/{id}/extend',
    'POST:/log-sheets/{id}/takeover',
    'GET:/log-sheets/{id}/fill',
    'POST:/log-sheets/{id}/complete',
    'GET:/my-inbox',
    'GET:/reports',
    'GET:/log-sheet-templates',
    'POST:/log-sheet-templates',
    'GET:/api/master-data',
    'POST:/api/log-sheets/batch',
    'GET:/api/log-sheets/inbox',
    'POST:/api/log-sheets/{id}/claim',
    'POST:/api/log-sheets/{id}/release',
    'POST:/api/log-sheets/{id}/assign',
    'POST:/api/log-sheets/{id}/reassign',
    'GET:/api/operational-units/{unitId}/operators',
    'GET:/api/asset-entries/nfc/{nfcTagId}',
    'GET:/api/bootstrap',
    'GET:/api/log-sheets/{id}/bundle'
);

-- OPERATOR → claim/release + mobile completion only (no web fill/complete)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'OPERATOR' AND p.code IN (
    'GET:/log-sheets',
    'GET:/log-sheets/{id}',
    'POST:/log-sheets/{id}/claim',
    'POST:/log-sheets/{id}/release',
    'GET:/my-inbox',
    'GET:/api/master-data',
    'POST:/api/log-sheets/batch',
    'GET:/api/log-sheets/inbox',
    'POST:/api/log-sheets/{id}/claim',
    'POST:/api/log-sheets/{id}/release',
    'GET:/api/asset-entries/nfc/{nfcTagId}',
    'GET:/api/bootstrap',
    'GET:/api/log-sheets/{id}/bundle'
);

-- SENIOR_OPERATOR → OPERATOR permissions + web fill/complete
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SENIOR_OPERATOR' AND p.code IN (
    'GET:/log-sheets',
    'GET:/log-sheets/{id}',
    'POST:/log-sheets/{id}/claim',
    'POST:/log-sheets/{id}/release',
    'GET:/log-sheets/{id}/fill',
    'POST:/log-sheets/{id}/complete',
    'GET:/my-inbox',
    'GET:/api/master-data',
    'POST:/api/log-sheets/batch',
    'GET:/api/log-sheets/inbox',
    'POST:/api/log-sheets/{id}/claim',
    'POST:/api/log-sheets/{id}/release',
    'GET:/api/asset-entries/nfc/{nfcTagId}',
    'GET:/api/bootstrap',
    'GET:/api/log-sheets/{id}/bundle'
);
