-- =============================================================================
-- backend-offline-first — consolidated schema (V1)
--
-- Single Flyway migration for a fresh database. Covers:
--   • Identity & RBAC (users, roles, permissions, unit staff links)
--   • Mobile-API session registry (api_sessions) for revocable, single-session JWTs
--   • Asset hierarchy master data (locations → systems → main/sub functions)
--   • Asset classes, field definitions, and physical asset entries
--   • Operational work: log-sheet templates, sheets, entries, action audit, void submissions
--     (including the CANCELLED lifecycle status — cancelled_at column)
--   • NFC fault reports (nfc_fault_reports) — unlocks per-asset manual entry when a tag
--     is broken/missing; log_sheet_entries.entry_source / filled_by_user_id record how
--     and by whom each entry was actually filled
--   • Asset operational status (asset_entries.status) — schema-only placeholder for a
--     future ON/OFF/IDLE/MAINTENANCE-style field, distinct from the active flag
--   • Uniqueness on user contact fields (national_code, phone_number, nfc_tag_id) —
--     each must be blank or unique, same convention as other business keys
--   • Generic entity audit_log and async Excel import_jobs
--   • Ops/monitoring, web-session, and login-attempt admin permissions
--
-- Conventions:
--   • Primary keys are BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   • Business / natural keys remain VARCHAR (code, username, local_id, nfc_tag_id, …).
--   • Timestamps are epoch millis (BIGINT), not TIMESTAMP columns.
--   • Case-insensitive uniqueness for master codes/tags/names uses UNIQUE INDEX on LOWER(…).
--   • Foreign keys default to ON DELETE RESTRICT so parents with dependents cannot be removed.
--     Cascades are used only for child rows that are meaningless without the parent
--     (log_sheet_entries, log_sheet_action_log, log_sheet_void_submissions, import_job_errors).
--   • Permission model: one permissions row per HTTP endpoint; code = METHOD:path.
-- =============================================================================

-- =============================================================================
-- TABLE: users
-- Application accounts for the admin web UI and mobile field operators.
-- Hard-delete is blocked in application logic (and by FKs) once the user has
-- participated in log sheets, audits, or imports; prefer setting active=false.
--
-- Columns:
--   username        Unique login name (exact match; application may trim).
--   password_hash   Encoded credential for LOCAL / HYBRID users.
--   auth_type       LOCAL | ACTIVE_DIRECTORY | HYBRID (CHECK constraint).
--   full_name       Display name (optional).
--   national_code   Optional national ID (max 15); blank or unique (ux_users_national_code).
--   phone_number    Optional phone (max 15); blank or unique (ux_users_phone_number).
--   nfc_tag_id      Optional NFC identifier for the person (max 50); blank or unique,
--                   case-insensitive (ux_users_nfc_tag_id_lower).
--   active          Soft enable/disable flag; inactive users cannot authenticate.
--   created_at / updated_at  Epoch millis.
-- =============================================================================
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    auth_type     VARCHAR(32)  NOT NULL DEFAULT 'LOCAL',
    full_name     VARCHAR(255),
    national_code VARCHAR(15),
    phone_number  VARCHAR(15),
    nfc_tag_id    VARCHAR(50),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    BIGINT,
    updated_at    BIGINT,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_auth_type CHECK (auth_type IN ('LOCAL', 'ACTIVE_DIRECTORY', 'HYBRID'))
);

-- =============================================================================
-- TABLE: operational_units
-- Hierarchical organization tree (plant / department / shift areas).
-- Used to scope which locations, templates, and log sheets a unit-scoped role
-- (SUPERVISOR / OPERATOR / SENIOR_OPERATOR) may see or manage.
--
-- Columns:
--   code       Business code; case-insensitive unique via ux_operational_units_code_lower.
--   name       Display name.
--   parent_id  Self-FK to another unit (NULL = root). ON DELETE RESTRICT.
-- =============================================================================
CREATE TABLE operational_units (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(255) NOT NULL,
    name       VARCHAR(255),
    parent_id  BIGINT,
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- TABLE: unit_supervisors
-- Many-to-many: which users supervise which operational units.
-- Composite PK (unit_id, user_id). Both FKs ON DELETE RESTRICT.
-- Service layer uses this to authorize supervisor-only log-sheet actions.
-- =============================================================================
CREATE TABLE unit_supervisors (
    unit_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (unit_id, user_id)
);

-- =============================================================================
-- TABLE: unit_operators
-- Many-to-many: which users operate within which operational units.
-- Same shape as unit_supervisors; drives operator inbox / claim eligibility.
-- =============================================================================
CREATE TABLE unit_operators (
    unit_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (unit_id, user_id)
);

-- =============================================================================
-- TABLE: api_sessions
-- Server-side registry of issued mobile-API JWTs (stateful control on top of an
-- otherwise-stateless token): every issued token is recorded by its `jti` claim,
-- an administrator can list devices and revoke individual sessions, and a user
-- may hold at most ONE active session (logging in on a second device supersedes
-- the first — enforced in ApiSessionService). Token lifetime itself lives in
-- app_settings ('auth.jwt.expiry_minutes'). Rows are kept after revocation/expiry
-- so the admin panel can show login history; JwtAuthenticationFilter treats a
-- token as valid only while the matching row has revoked_at IS NULL and
-- expires_at > now.
--
-- Columns:
--   jti           Unique token id (JWT "jti" claim) — the lookup key per request.
--   device_label  Client-supplied device name (optional; from the login payload).
--   user_agent    Raw User-Agent header, truncated — helps identify the tablet.
--   revoke_reason ADMIN | SUPERSEDED (new login on another device) | LOGOUT.
-- =============================================================================
CREATE TABLE api_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti           VARCHAR(64)  NOT NULL,
    user_id       BIGINT       NOT NULL,
    username      VARCHAR(255),
    device_label  VARCHAR(255),
    user_agent    VARCHAR(512),
    ip_address    VARCHAR(64),
    issued_at     BIGINT       NOT NULL,
    expires_at    BIGINT       NOT NULL,
    last_seen_at  BIGINT,
    revoked_at    BIGINT,
    revoked_by    BIGINT,
    revoke_reason VARCHAR(32),
    CONSTRAINT uk_api_sessions_jti UNIQUE (jti)
);

-- =============================================================================
-- TABLE: permissions
-- Atomic access rights for Spring Security @PreAuthorize checks.
-- One row per HTTP endpoint; code format is METHOD:path (e.g. GET:/users).
-- Seeded later in this migration; assigned to roles via role_permissions.
--
-- Columns:
--   code           Unique permission key (METHOD:path).
--   name           Persian (or UI) label for admin role editor.
--   category       Grouping: general | admin | organization | master-data |
--                  operational | reports | api.
--   http_method    GET / POST / … (informational; mirrors code).
--   endpoint_path  Path pattern as used by the web/API layer.
-- =============================================================================
CREATE TABLE permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(255) NOT NULL,
    name          VARCHAR(255),
    category      VARCHAR(255),
    http_method   VARCHAR(10),
    endpoint_path VARCHAR(512),
    CONSTRAINT uk_permissions_code UNIQUE (code)
);

-- =============================================================================
-- TABLE: roles
-- Named permission bundles. system_role=true rows are seed roles and must not
-- be deleted by administrators (protected in application code).
-- =============================================================================
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    system_role BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  BIGINT,
    updated_at  BIGINT,
    CONSTRAINT uk_roles_code UNIQUE (code)
);

-- =============================================================================
-- TABLE: role_permissions
-- Join table: which permissions belong to which role.
-- Composite PK; FKs ON DELETE RESTRICT (cannot drop a role/permission while linked).
-- =============================================================================
CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

-- =============================================================================
-- TABLE: user_roles
-- Join table: which roles are assigned to which user.
-- Composite PK; FKs ON DELETE RESTRICT.
-- =============================================================================
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- =============================================================================
-- TABLE: app_settings
-- Key/value runtime configuration edited from the admin Settings page.
-- Seeded defaults: Excel export row cap, audit retention days, JWT expiry minutes.
-- =============================================================================
CREATE TABLE app_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    value       VARCHAR(500) NOT NULL,
    updated_at  BIGINT
);

INSERT INTO app_settings (setting_key, value, updated_at) VALUES
('excel.export.max_rows', '10000', 0),
('audit.retention.days', '90', 0),
('auth.jwt.expiry_minutes', '480', 0);

-- =============================================================================
-- TABLE: locations
-- Hierarchical site / area / room master data under the asset plant hierarchy.
-- parent_id forms a location tree (ON DELETE RESTRICT — delete children first).
-- code is case-insensitive unique (ux_locations_code_lower).
--
-- Responsible operational units live in the location_units join table below — a
-- location can be owned by SEVERAL units (mirrors how one unit has several
-- supervisors/operators). There is deliberately no unit_id column here.
-- =============================================================================
CREATE TABLE locations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(255) NOT NULL,
    name       VARCHAR(255),
    name_fa    VARCHAR(255),
    parent_id  BIGINT,
    status     VARCHAR(30),
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- TABLE: location_units
-- Many-to-many: which operational units are responsible for which locations.
-- Composite PK (location_id, unit_id); same shape as unit_supervisors /
-- unit_operators. This is the root of every unit-scope walk:
--   unit → location_units → location tree → systems → main/sub functions → assets
-- (see AssetUnitScopeSql.SCOPED_SUBFUNCTIONS_CTE).
--
-- A location with no row here belongs to no unit and is therefore invisible to
-- unit-scoped roles — only ADMIN / HIGH_USER see it.
-- =============================================================================
CREATE TABLE location_units (
    location_id BIGINT NOT NULL,
    unit_id     BIGINT NOT NULL,
    PRIMARY KEY (location_id, unit_id)
);

-- =============================================================================
-- TABLE: plant_systems
-- Physical or logical plant systems hanging under a location (and optionally
-- nested under a parent plant system). Part of log-sheet template scope trees.
-- code is case-insensitive unique; name is required.
-- =============================================================================
CREATE TABLE plant_systems (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    name_fa     VARCHAR(255),
    parent_id   BIGINT,
    location_id BIGINT,
    status      VARCHAR(30),
    created_at  BIGINT,
    updated_at  BIGINT
);

-- =============================================================================
-- TABLE: main_functions
-- Functional groupings that may hang under a plant system, another main function,
-- or directly under a location. Used when resolving which sub-functions (and thus
-- assets) fall inside a log-sheet template scope.
-- code is case-insensitive unique; name is required.
-- =============================================================================
CREATE TABLE main_functions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    name_fa     VARCHAR(255),
    parent_id   BIGINT,
    system_id   BIGINT,
    location_id BIGINT,
    status      VARCHAR(30),
    created_at  BIGINT,
    updated_at  BIGINT
);

-- =============================================================================
-- TABLE: sub_functions
-- Leaf (or nested) equipment / function nodes. Assets attach here via
-- asset_entries.sub_function_id (exactly one asset per sub-function — unique index).
-- When an asset NFC is blank, the app may copy tag (or code) as the NFC value.
--
-- Parentage: parent_id (nested sub-function), and/or main_function_id, system_id,
-- location_id depending on where the node is attached in the hierarchy.
--
-- Uniqueness: code and tag are each case-insensitive unique globally.
-- =============================================================================
CREATE TABLE sub_functions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(255) NOT NULL,
    name             VARCHAR(255),
    name_fa          VARCHAR(255),
    tag              VARCHAR(255) NOT NULL,
    parent_id        BIGINT,
    main_function_id BIGINT,
    system_id        BIGINT,
    location_id      BIGINT,
    status           VARCHAR(30),
    created_at       BIGINT,
    updated_at       BIGINT
);

-- =============================================================================
-- TABLE: asset_classes
-- Asset type / form schema container. name is case-insensitive unique.
-- The field list lives in field_definitions — there is deliberately no denormalized
-- copy here: a second source of truth for the same schema only invites drift.
-- =============================================================================
CREATE TABLE asset_classes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- TABLE: field_definitions
-- Dynamic form fields for one asset class (temperature, pressure, options, …).
-- Used when validating log-sheet entry form_data and when building mobile bundles.
--
-- Columns:
--   class_id    Owning asset class (FK RESTRICT).
--   field_key   Stable key inside the class; unique per class case-insensitively.
--   label       UI label.
--   data_type   Application field type string.
--   unit        Optional engineering unit.
--   required    Whether form_data must include this key.
--   validation  JSONB rules (ranges, options, danger bands, …).
--   sort_order  Display order.
--   version / deleted / synced  Soft-delete and mobile sync bookkeeping.
-- =============================================================================
CREATE TABLE field_definitions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id   BIGINT       NOT NULL,
    field_key  VARCHAR(255) NOT NULL,
    label      VARCHAR(255),
    data_type  VARCHAR(255),
    unit       VARCHAR(255),
    required   BOOLEAN      NOT NULL,
    validation JSONB,
    sort_order INTEGER,
    version    INTEGER,
    deleted    BOOLEAN      NOT NULL,
    synced     BOOLEAN      NOT NULL,
    created_at BIGINT,
    updated_at BIGINT
);

-- =============================================================================
-- TABLE: asset_entries
-- Physical assets (pumps, valves, …) scanned via NFC on the mobile app.
-- Looked up by GET /api/asset-entries/nfc/{nfcTagId}.
--
-- Rules:
--   • asset_code is required and case-insensitive unique.
--   • nfc_tag_id is optional but case-insensitive unique when present
--     (PostgreSQL UNIQUE INDEX allows multiple NULLs).
--   • sub_function_id is required. At most ONE ACTIVE asset per sub-function
--     (ux_asset_entries_active_sub_function, a PARTIAL unique index on `WHERE active`);
--     any number of INACTIVE assets may share the same sub-function. This models
--     equipment replacement: a broken pump is deactivated and kept for history while
--     its successor is attached to the very same sub-function.
--   • class_id selects the field schema for log-sheet generation.
--   • active=false keeps the row findable by NFC/sync but excludes the asset from
--     new log-sheet preview/generation scope queries. Deactivating an asset also
--     RELEASES an nfc_tag_id that was inherited from the sub-function (equal to its
--     tag or code) by clearing it — otherwise the successor asset, which inherits the
--     same value, would collide on ux_asset_entries_nfc_tag_id_lower. A tag the asset
--     owns in its own right (any other value) is kept: it is physically on that asset.
--   • status is a free-form, schema-only field for the asset's real-world operational
--     state (e.g. ON / OFF / IDLE / MAINTENANCE) — NOT the same concept as active.
--     No entity field, DTO, API, or UI reads/writes it yet; deliberately left without
--     a CHECK constraint or enum since the exact set of states isn't finalized.
--     locations / plant_systems / main_functions / sub_functions carry the same
--     schema-only `status` column, for the same reason.
--   • asset_name_fa is a reserved secondary (Persian) title, schema-only for now — the
--     same column exists as name_fa on the four hierarchy tables.
-- =============================================================================
CREATE TABLE asset_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code      VARCHAR(255) NOT NULL,
    nfc_tag_id      VARCHAR(255),
    -- Physical NFC chip serial / UID, e.g. "00:aa:34:9f:12:cd". Optional, but unique when
    -- supplied (ux_asset_entries_nfc_serial_lower). NOT the same thing as nfc_tag_id: the tag id
    -- is the LOGICAL lookup key and is inherited from the sub-function's tag when the asset has
    -- none of its own (and released again when the asset is deactivated), while this identifies
    -- the piece of hardware and is never inherited, derived, or released.
    nfc_serial      VARCHAR(255),
    class_id        BIGINT,
    asset_name      VARCHAR(255),
    asset_name_fa   VARCHAR(255),
    sub_function_id BIGINT       NOT NULL,
    description     VARCHAR(500),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    status          VARCHAR(30),
    created_at      BIGINT,
    updated_at      BIGINT
);

-- =============================================================================
-- TABLE: log_sheet_templates
-- Reusable definitions for generating round log sheets (manual or scheduled).
-- asset_selection_mode decides how a generated sheet's assets are chosen:
--   SCOPE    (default) — re-resolved on EVERY generation from scope_type + scope_id +
--                        class_id, so assets added to that scope later are picked up
--                        automatically.
--   EXPLICIT           — a FROZEN, hand-picked set stored in log_sheet_template_assets;
--                        the scope/class columns are not used to select assets. The list
--                        never changes on its own; the only filter applied at generation
--                        time is that inactive assets are skipped. This is the
--                        "custom log sheet, but scheduled" mode, so its assets may span
--                        several asset classes and class_id may be NULL.
--
-- Scope (scope_type + scope_id) selects a subtree of the asset hierarchy;
-- class_id filters which assets of that scope are included (SCOPE mode only).
-- operational_unit_id scopes who may manage/generate from this template, and is
-- copied onto every generated log_sheets row — it is the ONLY thing that decides
-- which unit sees/fills the resulting work.
--
-- restrict_scope_to_unit controls scope picking, not access:
--   TRUE  (default) — the scope must sit under a location owned by that unit;
--                     the pickers only offer that unit's hierarchy.
--   FALSE           — the scope may be anywhere in the plant. Used when a unit is
--                     deliberately made responsible for assets outside its own
--                     locations. Access is unaffected: the assigned unit still
--                     reaches the work through log_sheets.operational_unit_id, and
--                     no other unit gains visibility of those assets.
--
-- Scheduling (when generation_mode is schedule-driven):
--   recurrence_unit / recurrence_every / schedule_start_at / schedule_active /
--   next_run_at / last_run_at / completion_window_minutes.
-- name is case-insensitive unique. active=false disables generation.
-- =============================================================================
CREATE TABLE log_sheet_templates (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255) NOT NULL,
    description               VARCHAR(255),
    scope_type                VARCHAR(255),
    scope_id                  BIGINT,
    -- Required for SCOPE mode; NULL is allowed for EXPLICIT templates, whose hand-picked
    -- assets may span several classes (like a custom log sheet).
    class_id                  BIGINT,
    asset_selection_mode      VARCHAR(20)  NOT NULL DEFAULT 'SCOPE',
    operational_unit_id       BIGINT,
    restrict_scope_to_unit    BOOLEAN      NOT NULL DEFAULT TRUE,
    generation_mode           VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    recurrence_unit           VARCHAR(20),
    recurrence_every          INTEGER,
    schedule_start_at         BIGINT,
    schedule_active           BOOLEAN      NOT NULL DEFAULT FALSE,
    next_run_at               BIGINT,
    last_run_at               BIGINT,
    completion_window_minutes INTEGER,
    active                    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                BIGINT,
    updated_at                BIGINT
);

-- =============================================================================
-- TABLE: log_sheet_template_assets
-- The frozen asset set of an EXPLICIT template (ignored by SCOPE templates).
-- Composite PK (template_id, asset_id). The template side CASCADEs — the list is
-- meaningless without its template and is always rewritten wholesale on save. The
-- asset side RESTRICTs so an asset referenced by a template cannot be hard-deleted
-- (deactivate it instead: generation already skips inactive assets).
-- =============================================================================
CREATE TABLE log_sheet_template_assets (
    template_id BIGINT NOT NULL,
    asset_id    BIGINT NOT NULL,
    PRIMARY KEY (template_id, asset_id)
);

-- =============================================================================
-- TABLE: log_sheets
-- One generated unit of work (a round) derived from a template.
-- Server-authoritative lifecycle: PENDING → assigned/claimed → IN_PROGRESS →
-- COMPLETED / expired, etc. (exact status strings enforced in application code).
--
-- Timing notes:
--   completed_at  Device-authoritative (may be recorded offline, synced later).
--   synced_at     Server receive/persist time for the completion sync.
--
-- field_definitions_snapshot freezes the class field schema at generation time
-- so later field edits do not rewrite historical sheets.
-- =============================================================================
CREATE TABLE log_sheets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id         BIGINT,
    template_name       VARCHAR(255),
    scope_summary       VARCHAR(255),
    operational_unit_id BIGINT,
    status              VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    origin              VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    assignee_user_id    BIGINT,
    assignment_type     VARCHAR(30),
    assigned_by_user_id BIGINT,
    completed_by_user_id BIGINT,
    operator_name       VARCHAR(255),
    notes               VARCHAR(4000),
    due_at              BIGINT,
    assigned_at         BIGINT,
    claimed_at          BIGINT,
    started_at          BIGINT,
    completed_at        BIGINT,
    expired_at          BIGINT,
    cancelled_at        BIGINT,
    submitted_at        BIGINT,
    synced_at           BIGINT,
    draft_saved_at      BIGINT,
    sync_status         VARCHAR(255),
    field_definitions_snapshot JSONB,
    created_at          BIGINT,
    updated_at          BIGINT
);

-- =============================================================================
-- TABLE: log_sheet_entries
-- One row per asset included in a generated log sheet.
-- form_data JSONB holds operator measurements keyed by field_definitions.field_key.
-- Denormalized asset_name / nfc_tag_id / sub_function_code / sub_function_tag /
-- class_id snapshot identity for display and offline use.
-- Deleted with the parent sheet (ON DELETE CASCADE).
-- Asset FK is RESTRICT so assets referenced by historical sheets cannot be hard-deleted.
--
-- entry_source / filled_by_user_id record how and by whom this specific entry was
-- actually filled (web / PWA+NFC scan / PWA manual) — stamped server-side on submit,
-- and only re-stamped when the incoming form_data actually changed from what's
-- already stored (see LogSheetService gotcha on reassignment attribution leaks).
-- =============================================================================
CREATE TABLE log_sheet_entries (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id       BIGINT,
    asset_id           BIGINT,
    asset_name         VARCHAR(255),
    nfc_tag_id         VARCHAR(255),
    -- Snapshot of the asset's physical chip serial at generation time. Deliberately NOT unique:
    -- every generated sheet copies the same asset's serial, and the snapshot must survive the
    -- asset row being edited or deleted. Carried to the PWA in LogSheetEntryDto so an offline
    -- scan can match the chip UID without a round trip.
    nfc_serial         VARCHAR(255),
    sub_function_code  VARCHAR(255),
    sub_function_tag   VARCHAR(255),
    class_id           BIGINT,
    form_data          JSONB,
    entry_source       VARCHAR(20),
    filled_by_user_id  BIGINT,
    created_at         BIGINT,
    updated_at         BIGINT
);

-- =============================================================================
-- TABLE: log_sheet_action_log
-- Immutable lifecycle audit for a log sheet: claim, assign, reassign, release,
-- extend, takeover, complete, etc.
--
-- Columns:
--   action_at         Device / real-world event time.
--   recorded_at       Server persist time.
--   client_action_id  Idempotency key when the same offline action is replayed
--                     on sync (UNIQUE when set).
--   actor / from / to user FKs describe who performed or received the action.
-- Cascades when the parent log_sheet is deleted.
-- =============================================================================
CREATE TABLE log_sheet_action_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id     BIGINT       NOT NULL,
    action           VARCHAR(30)  NOT NULL,
    actor_user_id    BIGINT,
    from_user_id     BIGINT,
    to_user_id       BIGINT,
    source           VARCHAR(20),
    action_at        BIGINT       NOT NULL,
    recorded_at      BIGINT       NOT NULL,
    client_action_id VARCHAR(255),
    -- Optional free-text reason the actor gave ("why", not "what"). Always optional — the action
    -- succeeds with this left null. Supplied today by EXTEND / CANCEL / VOID / UNVOID /
    -- ADMIN_REOPEN from the web panel; the column itself is action-agnostic.
    comment          VARCHAR(1000),
    CONSTRAINT uk_lsal_client_action_id UNIQUE (client_action_id)
);

-- =============================================================================
-- TABLE: log_sheet_void_submissions
-- Late offline operator completions that arrived after another actor already
-- finished the sheet (e.g. supervisor takeover). Stored for forensic/history
-- purposes only — never overwrite the authoritative completed sheet.
-- payload JSONB keeps the rejected submission body. Cascades with the sheet.
-- =============================================================================
CREATE TABLE log_sheet_void_submissions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id         BIGINT NOT NULL,
    submitted_by_user_id BIGINT,
    completed_at         BIGINT,
    synced_at            BIGINT,
    reason               VARCHAR(255),
    payload              JSONB
);

-- =============================================================================
-- TABLE: nfc_fault_reports
-- One row per reported NFC scan failure for a (log_sheet_id, asset_id) pair:
-- lets an operator or supervisor record that an asset's tag could not be scanned
-- (missing, broken, or the device's own NFC hardware is unusable), which unlocks
-- a manual-entry fallback for that one asset within that one log sheet. Multiple
-- reports for the same pair are allowed (no unique constraint) — the unlock rule
-- is simply "at least one report exists", not "exactly one". Insert-only (never
-- edited or deleted except by ADMIN) — same audit philosophy as
-- log_sheet_void_submissions. status exists for future workflow states (e.g.
-- under review / resolved) but only 'OPEN' is used today. operational_unit_id is
-- denormalized from the log sheet at creation time for cheap unit-scoped listing
-- without a join. Cascades with the parent sheet.
-- =============================================================================
CREATE TABLE nfc_fault_reports (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id         BIGINT       NOT NULL,
    asset_id             BIGINT       NOT NULL,
    operational_unit_id  BIGINT,
    reported_by_user_id  BIGINT,
    reported_by_name     VARCHAR(255),
    source               VARCHAR(20)  NOT NULL,
    reason               VARCHAR(2000),
    status               VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_at           BIGINT       NOT NULL,
    synced_at            BIGINT,
    client_action_id     VARCHAR(255),
    local_id             VARCHAR(255),
    CONSTRAINT uk_nfc_fault_reports_client_action_id UNIQUE (client_action_id)
);

-- =============================================================================
-- TABLE: audit_log
-- Generic field-level change history for master and operational entities.
-- Written by RepositoryAuditAspect (async). changes is JSONB array of
-- {field, oldValue, newValue}. actor_user_id FK RESTRICT (users with audit
-- history cannot be hard-deleted).
-- Indexed for retention purge (recorded_at) and entity drill-down.
-- =============================================================================
CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     VARCHAR(100) NOT NULL,
    entity_id       VARCHAR(255),
    action          VARCHAR(20)  NOT NULL,
    actor_user_id   BIGINT,
    actor_username  VARCHAR(255),
    source          VARCHAR(20),
    request_id      VARCHAR(64),
    changes         JSONB,
    recorded_at     BIGINT       NOT NULL
);

-- =============================================================================
-- TABLE: import_jobs
-- Async batch Excel import jobs (admin Batch Import UI).
-- The uploaded file is stored on disk under app.import.storage-path while the job
-- is PENDING/RUNNING; deleted when the job finishes (or rejected early).
-- Progress counters and status drive the polling UI.
--
-- Columns:
--   job_uuid             Public UUID for API/UI (UNIQUE).
--   entity_type          Which importer to run (locations, assets, users, …).
--   status               PENDING | RUNNING | COMPLETED | FAILED | CANCELLED.
--   file_*               Original name, absolute path, size.
--   total_rows / processed_rows / success_count / error_count  Progress.
--   submitted_by_user_id Who started the job (FK RESTRICT).
-- =============================================================================
CREATE TABLE import_jobs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_uuid             VARCHAR(36)   NOT NULL,
    entity_type          VARCHAR(64)   NOT NULL,
    status               VARCHAR(32)   NOT NULL,
    file_name            VARCHAR(512)  NOT NULL,
    file_path            VARCHAR(1024) NOT NULL,
    file_size            BIGINT        NOT NULL DEFAULT 0,
    total_rows           INT           NOT NULL DEFAULT 0,
    processed_rows       INT           NOT NULL DEFAULT 0,
    success_count        INT           NOT NULL DEFAULT 0,
    error_count          INT           NOT NULL DEFAULT 0,
    submitted_by_user_id BIGINT        NOT NULL,
    error_message        TEXT,
    created_at           BIGINT        NOT NULL,
    started_at           BIGINT,
    completed_at         BIGINT,
    CONSTRAINT uk_import_jobs_uuid UNIQUE (job_uuid)
);

-- =============================================================================
-- TABLE: import_job_errors
-- Per-row validation errors for an import job (English message_en; UI may translate).
-- ON DELETE CASCADE with import_jobs so deleting a job clears its error rows.
-- Cap on stored errors is enforced in application config (app.import.max-stored-errors).
-- =============================================================================
CREATE TABLE import_job_errors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     BIGINT        NOT NULL,
    row_num    INT           NOT NULL,
    message_en VARCHAR(1024) NOT NULL,
    CONSTRAINT fk_import_job_errors_job FOREIGN KEY (job_id) REFERENCES import_jobs (id) ON DELETE CASCADE
);

-- =============================================================================
-- FOREIGN KEYS
-- Policy: ON DELETE RESTRICT blocks removing a parent while dependents exist
-- (application shows Persian messages via ErrorTranslator for known constraint names).
-- Exceptions: CASCADE for pure child rows of a log sheet or import job.
-- =============================================================================

-- Operational unit tree + staff membership
ALTER TABLE operational_units
    ADD CONSTRAINT fk_operational_units_parent
        FOREIGN KEY (parent_id) REFERENCES operational_units (id) ON DELETE RESTRICT;

ALTER TABLE unit_supervisors
    ADD CONSTRAINT fk_unit_supervisors_unit
        FOREIGN KEY (unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_unit_supervisors_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE unit_operators
    ADD CONSTRAINT fk_unit_operators_unit
        FOREIGN KEY (unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_unit_operators_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT;

-- Mobile-API session registry — CASCADE (unlike the RESTRICT default) because a
-- session row is meaningless once its user is gone; there's no "historical session
-- of a deleted user" concern the way there is for audit/log-sheet actor references.
ALTER TABLE api_sessions
    ADD CONSTRAINT fk_api_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- RBAC joins
ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE RESTRICT;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT;

-- Asset hierarchy trees
ALTER TABLE locations
    ADD CONSTRAINT fk_locations_parent
        FOREIGN KEY (parent_id) REFERENCES locations (id) ON DELETE RESTRICT;

-- Location ↔ unit ownership. The location side CASCADEs (the link is meaningless
-- without the location and is always rewritten wholesale when a location is saved);
-- the unit side RESTRICTs so a unit that still owns locations cannot be deleted —
-- same guarantee the old locations.unit_id FK gave.
ALTER TABLE location_units
    ADD CONSTRAINT fk_location_units_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_location_units_unit
        FOREIGN KEY (unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT;

ALTER TABLE plant_systems
    ADD CONSTRAINT fk_plant_systems_parent
        FOREIGN KEY (parent_id) REFERENCES plant_systems (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_plant_systems_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT;

ALTER TABLE main_functions
    ADD CONSTRAINT fk_main_functions_parent
        FOREIGN KEY (parent_id) REFERENCES main_functions (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_main_functions_system
        FOREIGN KEY (system_id) REFERENCES plant_systems (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_main_functions_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT;

ALTER TABLE sub_functions
    ADD CONSTRAINT fk_sub_functions_parent
        FOREIGN KEY (parent_id) REFERENCES sub_functions (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_sub_functions_main_function
        FOREIGN KEY (main_function_id) REFERENCES main_functions (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_sub_functions_system
        FOREIGN KEY (system_id) REFERENCES plant_systems (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_sub_functions_location
        FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT;

-- Assets & legacy records
ALTER TABLE field_definitions
    ADD CONSTRAINT fk_field_definitions_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT;

ALTER TABLE asset_entries
    ADD CONSTRAINT fk_asset_entries_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_asset_entries_sub_function
        FOREIGN KEY (sub_function_id) REFERENCES sub_functions (id) ON DELETE RESTRICT;

-- Log sheets
ALTER TABLE log_sheet_templates
    ADD CONSTRAINT fk_log_sheet_templates_unit
        FOREIGN KEY (operational_unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheet_templates_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_template_assets
    ADD CONSTRAINT fk_lsta_template
        FOREIGN KEY (template_id) REFERENCES log_sheet_templates (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_lsta_asset
        FOREIGN KEY (asset_id) REFERENCES asset_entries (id) ON DELETE RESTRICT;

ALTER TABLE log_sheets
    ADD CONSTRAINT fk_log_sheets_template
        FOREIGN KEY (template_id) REFERENCES log_sheet_templates (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheets_unit
        FOREIGN KEY (operational_unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheets_assignee_user
        FOREIGN KEY (assignee_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheets_assigned_by_user
        FOREIGN KEY (assigned_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheets_completed_by_user
        FOREIGN KEY (completed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_entries
    ADD CONSTRAINT fk_log_sheet_entries_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_log_sheet_entries_asset
        FOREIGN KEY (asset_id) REFERENCES asset_entries (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheet_entries_class
        FOREIGN KEY (class_id) REFERENCES asset_classes (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_log_sheet_entries_filled_by_user
        FOREIGN KEY (filled_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_action_log
    ADD CONSTRAINT fk_lsal_log_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_lsal_actor_user
        FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_lsal_from_user
        FOREIGN KEY (from_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_lsal_to_user
        FOREIGN KEY (to_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_void_submissions
    ADD CONSTRAINT fk_lsvs_log_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_lsvs_submitted_by_user
        FOREIGN KEY (submitted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE nfc_fault_reports
    ADD CONSTRAINT fk_nfc_fault_reports_log_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_nfc_fault_reports_asset
        FOREIGN KEY (asset_id) REFERENCES asset_entries (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_nfc_fault_reports_unit
        FOREIGN KEY (operational_unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_nfc_fault_reports_reported_by_user
        FOREIGN KEY (reported_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

-- Audit & import
ALTER TABLE audit_log
    ADD CONSTRAINT fk_audit_log_actor_user
        FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE import_jobs
    ADD CONSTRAINT fk_import_jobs_submitted_by_user
        FOREIGN KEY (submitted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

-- =============================================================================
-- INDEXES
-- Naming:
--   idx_*  Non-unique btree indexes for filters, joins, sync-by-updated_at, trees.
--   ux_*   Unique indexes (often on LOWER(column) for case-insensitive business keys).
-- =============================================================================

-- --- Users: contact fields must be blank or unique ---
-- Standard Postgres unique indexes already permit unlimited NULL rows (NULL is
-- never equal to NULL), so no WHERE-based partial index is needed here.
CREATE UNIQUE INDEX ux_users_national_code ON users (national_code);
CREATE UNIQUE INDEX ux_users_phone_number ON users (phone_number);
CREATE UNIQUE INDEX ux_users_nfc_tag_id_lower ON users (LOWER(nfc_tag_id));

-- --- Hierarchy master data: sync deltas (updated_at) + tree walks (parent_id) ---
CREATE INDEX idx_locations_updated_at ON locations (updated_at);
CREATE INDEX idx_locations_parent_id ON locations (parent_id);
-- Case-insensitive unique business code for locations
CREATE UNIQUE INDEX ux_locations_code_lower ON locations (LOWER(code));

CREATE INDEX idx_plant_systems_updated_at ON plant_systems (updated_at);
CREATE INDEX idx_plant_systems_parent_id ON plant_systems (parent_id);
CREATE UNIQUE INDEX ux_plant_systems_code_lower ON plant_systems (LOWER(code));
-- Scope/join helper: systems under a location
CREATE INDEX idx_plant_systems_location_id ON plant_systems (location_id);

CREATE INDEX idx_main_functions_updated_at ON main_functions (updated_at);
CREATE INDEX idx_main_functions_parent_id ON main_functions (parent_id);
CREATE UNIQUE INDEX ux_main_functions_code_lower ON main_functions (LOWER(code));
CREATE INDEX idx_main_functions_location_id ON main_functions (location_id);
CREATE INDEX idx_main_functions_system_id ON main_functions (system_id);

CREATE INDEX idx_sub_functions_updated_at ON sub_functions (updated_at);
CREATE UNIQUE INDEX ux_sub_functions_code_lower ON sub_functions (LOWER(code));
CREATE UNIQUE INDEX ux_sub_functions_tag_lower ON sub_functions (LOWER(tag));
CREATE INDEX idx_sub_functions_parent_id ON sub_functions (parent_id);
-- Scope SQL / hierarchy resolution joins
CREATE INDEX idx_sub_functions_location_id ON sub_functions (location_id);
CREATE INDEX idx_sub_functions_system_id ON sub_functions (system_id);
CREATE INDEX idx_sub_functions_main_function_id ON sub_functions (main_function_id);

-- --- Asset classes & fields ---
CREATE INDEX idx_asset_classes_updated_at ON asset_classes (updated_at);
CREATE UNIQUE INDEX ux_asset_classes_name_lower ON asset_classes (LOWER(name));

CREATE INDEX idx_field_definitions_updated_at ON field_definitions (updated_at);
-- Load all fields for a class (bundle / form schema)
CREATE INDEX idx_field_definitions_class_id ON field_definitions (class_id);
-- field_key unique within a class (case-insensitive)
CREATE UNIQUE INDEX ux_field_definitions_class_key_lower ON field_definitions (class_id, LOWER(field_key));

-- --- Asset entries ---
CREATE INDEX idx_asset_entries_updated_at ON asset_entries (updated_at);
CREATE INDEX idx_asset_entries_class_id ON asset_entries (class_id);
-- At most one ACTIVE asset per sub-function. Inactive rows are deliberately exempt:
-- when a pump is replaced, the old asset is deactivated and stays in place for history
-- while its successor takes over the same sub-function. See the table comment above.
CREATE UNIQUE INDEX ux_asset_entries_active_sub_function ON asset_entries (sub_function_id)
    WHERE active;
-- Composite for class + sub-function scoped listings
CREATE INDEX idx_asset_entries_class_sub_function ON asset_entries (class_id, sub_function_id);
CREATE UNIQUE INDEX ux_asset_entries_asset_code_lower ON asset_entries (LOWER(asset_code));
-- Multiple NULL nfc_tag_id values are allowed by PostgreSQL unique indexes
CREATE UNIQUE INDEX ux_asset_entries_nfc_tag_id_lower ON asset_entries (LOWER(nfc_tag_id));
-- Same shape for the physical chip serial: optional, but unique when supplied. Non-partial on
-- purpose — a retired asset keeps the chip it was fitted with, so unlike the sub-function slot
-- this is not limited to active rows. NULLs are distinct, so any number of assets may have none.
CREATE UNIQUE INDEX ux_asset_entries_nfc_serial_lower ON asset_entries (LOWER(nfc_serial));

-- --- Operational units & location→unit ---
CREATE INDEX idx_operational_units_updated_at ON operational_units (updated_at);
CREATE INDEX idx_operational_units_parent_id ON operational_units (parent_id);
CREATE UNIQUE INDEX ux_operational_units_code_lower ON operational_units (LOWER(code));
-- Reverse lookup on the location↔unit join table (PK already covers location_id leading).
-- unit → locations is the hot direction: every unit-scope walk starts there.
CREATE INDEX idx_location_units_unit_id ON location_units (unit_id);

-- Reverse lookups on unit staff join tables (PK already covers unit_id leading)
CREATE INDEX idx_unit_supervisors_user_id ON unit_supervisors (user_id);
CREATE INDEX idx_unit_operators_user_id ON unit_operators (user_id);

-- --- Mobile-API session registry ---
CREATE INDEX idx_api_sessions_user_id ON api_sessions (user_id);
CREATE INDEX idx_api_sessions_expires_at ON api_sessions (expires_at);
-- Partial index: the hot path is "active sessions of this user" during login.
CREATE INDEX idx_api_sessions_active ON api_sessions (user_id) WHERE revoked_at IS NULL;

-- --- Log sheet templates & sheets ---
CREATE INDEX idx_log_sheet_templates_updated_at ON log_sheet_templates (updated_at);
CREATE UNIQUE INDEX ux_log_sheet_templates_name_lower ON log_sheet_templates (LOWER(name));
-- Scheduler poll: find due templates by next_run_at
CREATE INDEX idx_log_sheet_templates_next_run_at ON log_sheet_templates (next_run_at);
CREATE INDEX idx_log_sheet_templates_operational_unit_id ON log_sheet_templates (operational_unit_id);
-- Reverse lookup: "which templates reference this asset" (delete guards / impact checks).
-- The PK already covers template_id → assets, the hot direction at generation time.
CREATE INDEX idx_lsta_asset_id ON log_sheet_template_assets (asset_id);

CREATE INDEX idx_log_sheets_operational_unit_id ON log_sheets (operational_unit_id);
CREATE INDEX idx_log_sheets_assignee_user_id ON log_sheets (assignee_user_id);
CREATE INDEX idx_log_sheets_status ON log_sheets (status);
-- The supervisor team-open inbox filters by unit AND status together; the two single
-- column indexes above cannot serve that as cheaply as one composite.
CREATE INDEX idx_log_sheets_unit_status ON log_sheets (operational_unit_id, status);
CREATE INDEX idx_log_sheets_due_at ON log_sheets (due_at);

CREATE INDEX idx_log_sheet_entries_log_sheet_id ON log_sheet_entries (log_sheet_id);
CREATE INDEX idx_log_sheet_entries_asset_id ON log_sheet_entries (asset_id);

CREATE INDEX idx_lsal_log_sheet_id ON log_sheet_action_log (log_sheet_id);
CREATE INDEX idx_lsvs_log_sheet_id ON log_sheet_void_submissions (log_sheet_id);

CREATE INDEX idx_nfc_fault_reports_log_sheet_id ON nfc_fault_reports (log_sheet_id);
CREATE INDEX idx_nfc_fault_reports_asset_id ON nfc_fault_reports (asset_id);
CREATE INDEX idx_nfc_fault_reports_unit_id ON nfc_fault_reports (operational_unit_id);

-- --- Audit: retention purge + entity history pages ---
CREATE INDEX idx_audit_log_recorded_at ON audit_log (recorded_at DESC);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);

-- --- RBAC join helpers (non-leading PK columns) ---
CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);

-- --- Import jobs: user history + status board ---
CREATE INDEX idx_import_jobs_user_created ON import_jobs (submitted_by_user_id, created_at DESC);
CREATE INDEX idx_import_jobs_status ON import_jobs (status);
CREATE INDEX idx_import_job_errors_job_id ON import_job_errors (job_id);

-- =============================================================================
-- SEED: permissions — one row per HTTP endpoint (METHOD:path).
-- IDs are auto-assigned; role_permissions joins by permission / role codes.
-- =============================================================================
INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
-- General
('GET:/', 'داشبورد', 'general', 'GET', '/'),
-- Users
('GET:/users', 'لیست کاربران', 'admin', 'GET', '/users'),
('POST:/users', 'ایجاد کاربر', 'admin', 'POST', '/users'),
('POST:/users/{id}', 'ویرایش کاربر', 'admin', 'POST', '/users/{id}'),
('POST:/users/{id}/change-password', 'تغییر رمز کاربر', 'admin', 'POST', '/users/{id}/change-password'),
('POST:/users/{id}/delete', 'حذف کاربر', 'admin', 'POST', '/users/{id}/delete'),
('POST:/users/import', 'ورود کاربر از اکسل', 'admin', 'POST', '/users/import'),
('GET:/users/import-template', 'دانلود قالب اکسل کاربر', 'admin', 'GET', '/users/import-template'),
-- Roles
('GET:/roles', 'لیست نقش‌ها', 'admin', 'GET', '/roles'),
('POST:/roles', 'ایجاد نقش', 'admin', 'POST', '/roles'),
('POST:/roles/{id}', 'ویرایش نقش', 'admin', 'POST', '/roles/{id}'),
('POST:/roles/{id}/delete', 'حذف نقش', 'admin', 'POST', '/roles/{id}/delete'),
-- Settings
('GET:/settings', 'تنظیمات برنامه', 'admin', 'GET', '/settings'),
('POST:/settings', 'ذخیره تنظیمات برنامه', 'admin', 'POST', '/settings'),
('POST:/settings/audit-retention/run', 'اجرای پاکسازی audit', 'admin', 'POST', '/settings/audit-retention/run'),
('POST:/settings/audit-retention/cancel', 'توقف پاکسازی audit', 'admin', 'POST', '/settings/audit-retention/cancel'),
('GET:/audit-logs', 'مشاهده تاریخچه تغییرات', 'admin', 'GET', '/audit-logs'),
('GET:/batch-import', 'صفحه ورود دسته‌ای اکسل', 'admin', 'GET', '/batch-import'),
('POST:/batch-import', 'شروع ورود دسته‌ای اکسل', 'admin', 'POST', '/batch-import'),
('GET:/batch-import/jobs', 'لیست jobهای ورود اکسل', 'admin', 'GET', '/batch-import/jobs'),
-- Mobile API sessions (admin) — revocable, single-session-per-user JWT registry
('GET:/api-sessions', 'لیست نشست‌های اپ موبایل', 'admin', 'GET', '/api-sessions'),
('POST:/api-sessions/{id}/revoke', 'ابطال نشست اپ موبایل', 'admin', 'POST', '/api-sessions/{id}/revoke'),
('POST:/api-sessions/revoke-user/{userId}', 'ابطال همه نشست‌های یک کاربر', 'admin', 'POST', '/api-sessions/revoke-user/{userId}'),
-- Web panel sessions (admin) — form-login SessionRegistry admin page
('GET:/web-sessions', 'لیست نشست‌های وب', 'admin', 'GET', '/web-sessions'),
('POST:/web-sessions/{key}/expire', 'ابطال نشست وب', 'admin', 'POST', '/web-sessions/{key}/expire'),
-- Login-attempt throttle (admin)
('GET:/login-attempts', 'لیست تلاش‌های ورود ناموفق', 'admin', 'GET', '/login-attempts'),
('POST:/login-attempts/{username}/unlock', 'باز کردن قفل کاربر', 'admin', 'POST', '/login-attempts/{username}/unlock'),
-- Ops / monitoring (admin) — Actuator (liveness/readiness stay public via permitAll)
-- and springdoc-openapi (/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html)
('GET:/actuator/**', 'مانیتورینگ سیستم (Actuator)', 'admin', 'GET', '/actuator/**'),
('GET:/v3/api-docs/**', 'مستندات API (Swagger)', 'admin', 'GET', '/v3/api-docs/**'),
-- Operational units
('GET:/operational-units', 'لیست واحدهای عملیاتی', 'organization', 'GET', '/operational-units'),
('POST:/operational-units', 'ایجاد واحد عملیاتی', 'organization', 'POST', '/operational-units'),
('POST:/operational-units/{id}', 'ویرایش واحد عملیاتی', 'organization', 'POST', '/operational-units/{id}'),
('POST:/operational-units/{id}/delete', 'حذف واحد عملیاتی', 'organization', 'POST', '/operational-units/{id}/delete'),
('POST:/operational-units/import', 'ورود واحد عملیاتی از اکسل', 'organization', 'POST', '/operational-units/import'),
('GET:/operational-units/import-template', 'دانلود قالب اکسل واحد عملیاتی', 'organization', 'GET', '/operational-units/import-template'),
('POST:/operational-units/import-staff', 'ورود سرپرست/اپراتور واحد از اکسل', 'organization', 'POST', '/operational-units/import-staff'),
('GET:/operational-units/import-staff-template', 'دانلود قالب اکسل سرپرست/اپراتور', 'organization', 'GET', '/operational-units/import-staff-template'),
-- Locations
('GET:/locations', 'لیست مکان‌ها', 'master-data', 'GET', '/locations'),
('POST:/locations', 'ایجاد مکان', 'master-data', 'POST', '/locations'),
('POST:/locations/{id}', 'ویرایش مکان', 'master-data', 'POST', '/locations/{id}'),
('POST:/locations/{id}/delete', 'حذف مکان', 'master-data', 'POST', '/locations/{id}/delete'),
('POST:/locations/import', 'ورود مکان از اکسل', 'master-data', 'POST', '/locations/import'),
('GET:/locations/import-template', 'دانلود قالب اکسل مکان', 'master-data', 'GET', '/locations/import-template'),
-- Plant systems
('GET:/plant-systems', 'لیست سیستم‌های واحد', 'master-data', 'GET', '/plant-systems'),
('POST:/plant-systems', 'ایجاد سیستم واحد', 'master-data', 'POST', '/plant-systems'),
('POST:/plant-systems/{id}', 'ویرایش سیستم واحد', 'master-data', 'POST', '/plant-systems/{id}'),
('POST:/plant-systems/{id}/delete', 'حذف سیستم واحد', 'master-data', 'POST', '/plant-systems/{id}/delete'),
('POST:/plant-systems/import', 'ورود سیستم واحد از اکسل', 'master-data', 'POST', '/plant-systems/import'),
('GET:/plant-systems/import-template', 'دانلود قالب اکسل سیستم واحد', 'master-data', 'GET', '/plant-systems/import-template'),
-- Main functions
('GET:/main-functions', 'لیست توابع اصلی', 'master-data', 'GET', '/main-functions'),
('POST:/main-functions', 'ایجاد تابع اصلی', 'master-data', 'POST', '/main-functions'),
('POST:/main-functions/{id}', 'ویرایش تابع اصلی', 'master-data', 'POST', '/main-functions/{id}'),
('POST:/main-functions/{id}/delete', 'حذف تابع اصلی', 'master-data', 'POST', '/main-functions/{id}/delete'),
('POST:/main-functions/import', 'ورود تابع اصلی از اکسل', 'master-data', 'POST', '/main-functions/import'),
('GET:/main-functions/import-template', 'دانلود قالب اکسل تابع اصلی', 'master-data', 'GET', '/main-functions/import-template'),
-- Sub functions
('GET:/sub-functions', 'لیست توابع فرعی', 'master-data', 'GET', '/sub-functions'),
('POST:/sub-functions', 'ایجاد تابع فرعی', 'master-data', 'POST', '/sub-functions'),
('POST:/sub-functions/{id}', 'ویرایش تابع فرعی', 'master-data', 'POST', '/sub-functions/{id}'),
('POST:/sub-functions/{id}/delete', 'حذف تابع فرعی', 'master-data', 'POST', '/sub-functions/{id}/delete'),
('POST:/sub-functions/import', 'ورود تابع فرعی از اکسل', 'master-data', 'POST', '/sub-functions/import'),
('GET:/sub-functions/import-template', 'دانلود قالب اکسل تابع فرعی', 'master-data', 'GET', '/sub-functions/import-template'),
-- Asset classes
('GET:/asset-classes', 'لیست کلاس‌های دارایی', 'master-data', 'GET', '/asset-classes'),
('POST:/asset-classes', 'ایجاد کلاس دارایی', 'master-data', 'POST', '/asset-classes'),
('POST:/asset-classes/{id}', 'ویرایش کلاس دارایی', 'master-data', 'POST', '/asset-classes/{id}'),
('POST:/asset-classes/{id}/delete', 'حذف کلاس دارایی', 'master-data', 'POST', '/asset-classes/{id}/delete'),
('GET:/asset-classes/{classId}/fields', 'لیست فیلدهای کلاس', 'master-data', 'GET', '/asset-classes/{classId}/fields'),
('POST:/asset-classes/{classId}/fields', 'افزودن فیلد به کلاس', 'master-data', 'POST', '/asset-classes/{classId}/fields'),
('POST:/asset-classes/{classId}/fields/{fieldId}', 'ویرایش فیلد کلاس', 'master-data', 'POST', '/asset-classes/{classId}/fields/{fieldId}'),
('POST:/asset-classes/{classId}/fields/{fieldId}/delete', 'حذف فیلد کلاس', 'master-data', 'POST', '/asset-classes/{classId}/fields/{fieldId}/delete'),
-- Asset entries
('GET:/asset-entries', 'لیست دارایی‌ها', 'master-data', 'GET', '/asset-entries'),
('POST:/asset-entries', 'ایجاد دارایی', 'master-data', 'POST', '/asset-entries'),
('POST:/asset-entries/{id}', 'ویرایش دارایی', 'master-data', 'POST', '/asset-entries/{id}'),
('POST:/asset-entries/{id}/delete', 'حذف دارایی', 'master-data', 'POST', '/asset-entries/{id}/delete'),
('POST:/asset-entries/import', 'ورود دارایی از اکسل', 'master-data', 'POST', '/asset-entries/import'),
('GET:/asset-entries/import-template', 'دانلود قالب اکسل دارایی', 'master-data', 'GET', '/asset-entries/import-template'),
-- Log sheet templates
('GET:/log-sheet-templates', 'لیست قالب‌های لاگ', 'master-data', 'GET', '/log-sheet-templates'),
('POST:/log-sheet-templates', 'ایجاد قالب لاگ', 'master-data', 'POST', '/log-sheet-templates'),
('POST:/log-sheet-templates/{id}', 'ویرایش قالب لاگ', 'master-data', 'POST', '/log-sheet-templates/{id}'),
('POST:/log-sheet-templates/{id}/delete', 'حذف قالب لاگ', 'master-data', 'POST', '/log-sheet-templates/{id}/delete'),
-- Operational data
('GET:/log-sheets', 'لیست لاگ‌شیت‌ها', 'operational', 'GET', '/log-sheets'),
('GET:/log-sheets/{id}', 'جزئیات لاگ‌شیت', 'operational', 'GET', '/log-sheets/{id}'),
('POST:/log-sheets/generate', 'تولید دستی لاگ‌شیت از قالب', 'operational', 'POST', '/log-sheets/generate'),
('POST:/log-sheets/custom', 'ساخت لاگ‌شیت سفارشی', 'operational', 'POST', '/log-sheets/custom'),
('GET:/log-sheets/options/assets', 'گزینه‌های دارایی برای لاگ‌شیت سفارشی', 'operational', 'GET', '/log-sheets/options/assets'),
('GET:/log-sheets/options/units', 'گزینه‌های واحد عملیاتی برای لاگ‌شیت سفارشی', 'operational', 'GET', '/log-sheets/options/units'),
('POST:/log-sheets/{id}/claim', 'پیک‌آپ لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/claim'),
('POST:/log-sheets/{id}/release', 'برگرداندن لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/release'),
('POST:/log-sheets/{id}/assign', 'انتساب لاگ‌شیت به اپراتور', 'operational', 'POST', '/log-sheets/{id}/assign'),
('POST:/log-sheets/{id}/reassign', 'بازانتساب لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/reassign'),
('POST:/log-sheets/{id}/extend', 'تمدید مهلت لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/extend'),
('POST:/log-sheets/{id}/takeover', 'تصاحب لاگ‌شیت توسط سرپرست', 'operational', 'POST', '/log-sheets/{id}/takeover'),
('POST:/log-sheets/{id}/void', 'ابطال لاگ‌شیت تکمیل‌شده', 'operational', 'POST', '/log-sheets/{id}/void'),
('POST:/log-sheets/{id}/unvoid', 'بازگردانی لاگ‌شیت ابطال‌شده', 'operational', 'POST', '/log-sheets/{id}/unvoid'),
('POST:/log-sheets/{id}/reopen', 'باز کردن مجدد لاگ‌شیت تکمیل‌شده', 'operational', 'POST', '/log-sheets/{id}/reopen'),
('POST:/log-sheets/{id}/cancel', 'لغو لاگ‌شیت', 'operational', 'POST', '/log-sheets/{id}/cancel'),
('GET:/log-sheets/{id}/fill', 'فرم تکمیل لاگ‌شیت (وب)', 'operational', 'GET', '/log-sheets/{id}/fill'),
('POST:/log-sheets/{id}/complete', 'تکمیل لاگ‌شیت در وب', 'operational', 'POST', '/log-sheets/{id}/complete'),
('GET:/my-inbox', 'کارتابل من', 'operational', 'GET', '/my-inbox'),
('GET:/reports', 'گزارش‌گیری', 'reports', 'GET', '/reports'),
-- NFC fault reports
('GET:/nfc-fault-reports', 'لیست گزارش‌های خرابی NFC', 'operational', 'GET', '/nfc-fault-reports'),
('POST:/nfc-fault-reports', 'ثبت گزارش خرابی NFC', 'operational', 'POST', '/nfc-fault-reports'),
('POST:/nfc-fault-reports/{id}/delete', 'حذف گزارش خرابی NFC', 'admin', 'POST', '/nfc-fault-reports/{id}/delete'),
-- Mobile API
('POST:/api/log-sheets/batch', 'API — ارسال/تکمیل لاگ‌شیت', 'api', 'POST', '/api/log-sheets/batch'),
('GET:/api/log-sheets/inbox', 'API — کارتابل لاگ‌شیت', 'api', 'GET', '/api/log-sheets/inbox'),
('POST:/api/log-sheets/{id}/claim', 'API — پیک‌آپ لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/claim'),
('POST:/api/log-sheets/{id}/release', 'API — برگرداندن لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/release'),
('POST:/api/log-sheets/{id}/assign', 'API — انتساب لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/assign'),
('POST:/api/log-sheets/{id}/reassign', 'API — بازانتساب لاگ‌شیت', 'api', 'POST', '/api/log-sheets/{id}/reassign'),
('GET:/api/operational-units/{unitId}/operators', 'API — اپراتورهای واحد', 'api', 'GET', '/api/operational-units/{unitId}/operators'),
('GET:/api/asset-entries/nfc/{nfcTagId}', 'API — جستجوی NFC', 'api', 'GET', '/api/asset-entries/nfc/{nfcTagId}'),
('GET:/api/bootstrap', 'API — bootstrap اپ موبایل', 'api', 'GET', '/api/bootstrap'),
('GET:/api/log-sheets/{id}/bundle', 'API — بسته لاگ‌شیت', 'api', 'GET', '/api/log-sheets/{id}/bundle'),
('POST:/api/nfc-fault-reports/batch', 'API — ارسال گزارش خرابی NFC', 'api', 'POST', '/api/nfc-fault-reports/batch');

-- =============================================================================
-- SEED: default system roles (5)
-- ADMIN            — full access to everything.
-- HIGH_USER        — everything except the admin category (users, roles, settings),
--                    plus explicit batch-import permissions granted below.
-- SUPERVISOR       — unit-scoped: sees/manages only their own units and sub-units;
--                    may generate, assign/reassign, extend, takeover and complete work;
--                    may create log-sheet templates but not edit/delete them.
-- SENIOR_OPERATOR  — like OPERATOR but may also complete assigned work in the web UI.
-- OPERATOR         — unit-scoped: claim/release and complete work via mobile app only.
-- Supervisor-only actions are additionally gated by an is-supervisor-of-unit
-- relationship check in the service layer.
-- =============================================================================
INSERT INTO roles (code, name, description, system_role, created_at, updated_at) VALUES
('ADMIN',            'مدیر سیستم',    'دسترسی کامل به همه بخش‌ها',                        TRUE, 0, 0),
('HIGH_USER',        'کاربر ارشد',    'همه دسترسی‌ها به‌جز مدیریت کاربران و تنظیمات',       TRUE, 0, 0),
('SUPERVISOR',       'سرپرست',        'مدیریت کارها فقط در واحدهای تحت سرپرستی خود',        TRUE, 0, 0),
('SENIOR_OPERATOR',  'اپراتور ارشد',  'مثل اپراتور؛ تکمیل در وب و اپ موبایل',               TRUE, 0, 0),
('OPERATOR',         'اپراتور',       'پیک‌آپ و تکمیل لاگ‌شیت در اپ موبایل',                TRUE, 0, 0);

-- ADMIN → every permission
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ADMIN';

-- HIGH_USER → everything except admin category
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'HIGH_USER' AND p.category <> 'admin';

-- SUPERVISOR → full log-sheet lifecycle (supervisor actions gated by relationship)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SUPERVISOR' AND p.code IN (
    'GET:/log-sheets',
    'GET:/log-sheets/{id}',
    'POST:/log-sheets/generate',
    'POST:/log-sheets/custom',
    'GET:/log-sheets/options/assets',
    'GET:/log-sheets/options/units',
    'POST:/log-sheets/{id}/claim',
    'POST:/log-sheets/{id}/release',
    'POST:/log-sheets/{id}/assign',
    'POST:/log-sheets/{id}/reassign',
    'POST:/log-sheets/{id}/extend',
    'POST:/log-sheets/{id}/takeover',
    'POST:/log-sheets/{id}/void',
    'POST:/log-sheets/{id}/unvoid',
    'POST:/log-sheets/{id}/reopen',
    'POST:/log-sheets/{id}/cancel',
    'GET:/log-sheets/{id}/fill',
    'POST:/log-sheets/{id}/complete',
    'GET:/my-inbox',
    'GET:/reports',
    -- Templates are READ-ONLY for supervisors: creating/editing is ADMIN/HIGH_USER only.
    'GET:/log-sheet-templates',
    'POST:/api/log-sheets/batch',
    'GET:/api/log-sheets/inbox',
    'POST:/api/log-sheets/{id}/claim',
    'POST:/api/log-sheets/{id}/release',
    'POST:/api/log-sheets/{id}/assign',
    'POST:/api/log-sheets/{id}/reassign',
    'GET:/api/operational-units/{unitId}/operators',
    'GET:/api/asset-entries/nfc/{nfcTagId}',
    'GET:/api/bootstrap',
    'GET:/api/log-sheets/{id}/bundle'
);

-- OPERATOR → claim/release + mobile completion only (no web fill/complete)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'OPERATOR' AND p.code IN (
    'GET:/log-sheets',
    'GET:/log-sheets/{id}',
    'POST:/log-sheets/{id}/claim',
    'POST:/log-sheets/{id}/release',
    'GET:/my-inbox',
    'POST:/api/log-sheets/batch',
    'GET:/api/log-sheets/inbox',
    'POST:/api/log-sheets/{id}/claim',
    'POST:/api/log-sheets/{id}/release',
    'GET:/api/asset-entries/nfc/{nfcTagId}',
    'GET:/api/bootstrap',
    'GET:/api/log-sheets/{id}/bundle'
);

-- SENIOR_OPERATOR → OPERATOR permissions + web fill/complete
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SENIOR_OPERATOR' AND p.code IN (
    'GET:/log-sheets',
    'GET:/log-sheets/{id}',
    'POST:/log-sheets/{id}/claim',
    'POST:/log-sheets/{id}/release',
    'GET:/log-sheets/{id}/fill',
    'POST:/log-sheets/{id}/complete',
    'GET:/my-inbox',
    'POST:/api/log-sheets/batch',
    'GET:/api/log-sheets/inbox',
    'POST:/api/log-sheets/{id}/claim',
    'POST:/api/log-sheets/{id}/release',
    'GET:/api/asset-entries/nfc/{nfcTagId}',
    'GET:/api/bootstrap',
    'GET:/api/log-sheets/{id}/bundle'
);

-- NFC fault reports — ADMIN/HIGH_USER already covered by the blanket grants above
-- (the admin-only delete permission is 'admin' category, so HIGH_USER's category
-- filter correctly excludes it there too). SUPERVISOR/OPERATOR/SENIOR_OPERATOR use
-- explicit IN-lists like the rest of this file, so they need their own grants here.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SUPERVISOR' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);

-- OPERATOR / SENIOR_OPERATOR: can view (web, rarely used) and submit via mobile; no web create.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'OPERATOR' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SENIOR_OPERATOR' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);

-- HIGH_USER → batch import (admin category; not included in category-wide grant above)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'HIGH_USER' AND p.code IN (
    'GET:/batch-import',
    'POST:/batch-import',
    'GET:/batch-import/jobs'
);
