-- =============================================================================
-- V2 — API session registry (stateful JWT control for mobile/PWA clients)
--
-- Until now /api/** JWTs were purely stateless: the server could neither revoke
-- an issued token nor tell how many were outstanding. This migration introduces
-- a server-side registry so that:
--   * every issued token is recorded by its `jti` claim,
--   * an administrator can list devices and revoke individual sessions,
--   * a user may hold at most ONE active session (logging in on a second device
--     supersedes the first — enforced in ApiSessionService).
--
-- Token lifetime itself stays in app_settings ('auth.jwt.expiry_minutes').
-- =============================================================================

-- =============================================================================
-- TABLE: api_sessions
-- One row per issued mobile-API JWT. Rows are kept after revocation/expiry so
-- the admin panel can show login history; JwtAuthenticationFilter treats a token
-- as valid only while the matching row has revoked_at IS NULL and expires_at > now.
--
-- Columns:
--   jti           Unique token id (JWT "jti" claim) — the lookup key per request.
--   device_label  Client-supplied device name (optional; from the login payload).
--   user_agent    Raw User-Agent header, truncated — helps identify the tablet.
--   revoke_reason ADMIN | SUPERSEDED (new login on another device) | LOGOUT.
-- =============================================================================
CREATE TABLE api_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti           VARCHAR(64)  NOT NULL,
    user_id       BIGINT       NOT NULL,
    username      VARCHAR(255),
    device_label  VARCHAR(255),
    user_agent    VARCHAR(512),
    ip_address    VARCHAR(64),
    issued_at     BIGINT       NOT NULL,
    expires_at    BIGINT       NOT NULL,
    last_seen_at  BIGINT,
    revoked_at    BIGINT,
    revoked_by    BIGINT,
    revoke_reason VARCHAR(32),
    CONSTRAINT uk_api_sessions_jti UNIQUE (jti),
    CONSTRAINT fk_api_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_api_sessions_user_id ON api_sessions (user_id);
CREATE INDEX idx_api_sessions_expires_at ON api_sessions (expires_at);
-- Partial index: the hot path is "active sessions of this user" during login.
CREATE INDEX idx_api_sessions_active ON api_sessions (user_id) WHERE revoked_at IS NULL;

-- =============================================================================
-- SEED: permissions for the admin session-management page.
-- Category 'admin' keeps them out of the HIGH_USER category-wide grant, so only
-- ADMIN receives them (granted explicitly below).
-- =============================================================================
INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
('GET:/api-sessions', 'لیست نشست‌های اپ موبایل', 'admin', 'GET', '/api-sessions'),
('POST:/api-sessions/{id}/revoke', 'ابطال نشست اپ موبایل', 'admin', 'POST', '/api-sessions/{id}/revoke'),
('POST:/api-sessions/revoke-user/{userId}', 'ابطال همه نشست‌های یک کاربر', 'admin', 'POST', '/api-sessions/revoke-user/{userId}');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ADMIN' AND p.code IN (
    'GET:/api-sessions',
    'POST:/api-sessions/{id}/revoke',
    'POST:/api-sessions/revoke-user/{userId}'
);
