-- =============================================================================
-- V2: NFC fault reports + per-entry completion channel/authorship
--
-- Lets an operator or supervisor record that an asset's NFC tag could not be
-- scanned (missing, broken, or the device's NFC hardware itself is unusable)
-- for a specific log sheet, so the mobile app can unlock a manual-entry
-- fallback for that one asset without silently bypassing NFC verification.
-- Reports are insert-only (never edited or deleted except by ADMIN) — same
-- audit philosophy as log_sheet_void_submissions. `status` exists for future
-- workflow states (e.g. under review / resolved) but only 'OPEN' is used today.
--
-- Also adds entry_source / filled_by_user_id to log_sheet_entries so each
-- asset's reading records how it was captured (web / PWA+NFC scan / PWA
-- manual) and by whom — a step toward AGENTS.md gotcha #20 (per-entry
-- authorship on reassignment); stamped server-side on submit.
-- =============================================================================

-- =============================================================================
-- TABLE: nfc_fault_reports
-- One row per reported NFC scan failure for a (log_sheet_id, asset_id) pair.
-- Multiple reports for the same pair are allowed (no unique constraint) — the
-- unlock rule is simply "at least one report exists", not "exactly one".
-- operational_unit_id is denormalized from the log sheet at creation time for
-- cheap unit-scoped listing without a join. Cascades with the parent sheet.
-- =============================================================================
CREATE TABLE nfc_fault_reports (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_sheet_id         BIGINT       NOT NULL,
    asset_id             BIGINT       NOT NULL,
    operational_unit_id  BIGINT,
    reported_by_user_id  BIGINT,
    reported_by_name     VARCHAR(255),
    source               VARCHAR(20)  NOT NULL,
    reason               VARCHAR(2000),
    status               VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_at           BIGINT       NOT NULL,
    synced_at            BIGINT,
    client_action_id     VARCHAR(255),
    local_id             VARCHAR(255),
    CONSTRAINT uk_nfc_fault_reports_client_action_id UNIQUE (client_action_id)
);

ALTER TABLE log_sheet_entries
    ADD COLUMN entry_source      VARCHAR(20),
    ADD COLUMN filled_by_user_id BIGINT;

-- =============================================================================
-- FOREIGN KEYS
-- =============================================================================
ALTER TABLE nfc_fault_reports
    ADD CONSTRAINT fk_nfc_fault_reports_log_sheet
        FOREIGN KEY (log_sheet_id) REFERENCES log_sheets (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_nfc_fault_reports_asset
        FOREIGN KEY (asset_id) REFERENCES asset_entries (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_nfc_fault_reports_unit
        FOREIGN KEY (operational_unit_id) REFERENCES operational_units (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_nfc_fault_reports_reported_by_user
        FOREIGN KEY (reported_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE log_sheet_entries
    ADD CONSTRAINT fk_log_sheet_entries_filled_by_user
        FOREIGN KEY (filled_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

-- =============================================================================
-- INDEXES
-- =============================================================================
CREATE INDEX idx_nfc_fault_reports_log_sheet_id ON nfc_fault_reports (log_sheet_id);
CREATE INDEX idx_nfc_fault_reports_asset_id ON nfc_fault_reports (asset_id);
CREATE INDEX idx_nfc_fault_reports_unit_id ON nfc_fault_reports (operational_unit_id);

-- =============================================================================
-- PERMISSIONS
-- V1's blanket ADMIN/HIGH_USER grants (`SELECT ... FROM permissions` with no
-- code filter) only ran once, when V1 itself was applied — they do NOT
-- retroactively cover permissions inserted by this later migration. Every
-- role that should get these, including ADMIN and HIGH_USER, must be granted
-- explicitly here (this is the same pattern the original V2-V4 migrations
-- used before being folded into V1; it only stops being needed if this file
-- is ever folded into V1 too). The delete permission is 'admin' category and
-- is intentionally granted to ADMIN only — HIGH_USER is excluded.
-- =============================================================================
INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
('GET:/nfc-fault-reports', 'لیست گزارش‌های خرابی NFC', 'operational', 'GET', '/nfc-fault-reports'),
('POST:/nfc-fault-reports', 'ثبت گزارش خرابی NFC', 'operational', 'POST', '/nfc-fault-reports'),
('POST:/nfc-fault-reports/{id}/delete', 'حذف گزارش خرابی NFC', 'admin', 'POST', '/nfc-fault-reports/{id}/delete'),
('POST:/api/nfc-fault-reports/batch', 'API — ارسال گزارش خرابی NFC', 'api', 'POST', '/api/nfc-fault-reports/batch');

-- ADMIN: every permission above, including the admin-only delete.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ADMIN' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/nfc-fault-reports',
    'POST:/nfc-fault-reports/{id}/delete',
    'POST:/api/nfc-fault-reports/batch'
);

-- HIGH_USER: everything except the admin-only delete.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'HIGH_USER' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);

-- SUPERVISOR: can view + create via web, and submit via mobile.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SUPERVISOR' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);

-- OPERATOR: can view (web, rarely used) and submit via mobile; no web create.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'OPERATOR' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);

-- SENIOR_OPERATOR: same as OPERATOR for this feature.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SENIOR_OPERATOR' AND p.code IN (
    'GET:/nfc-fault-reports',
    'POST:/api/nfc-fault-reports/batch'
);
