-- =============================================================================
-- V4 — Integration API for third-party systems
--
-- WHAT THIS ADDS
--
--   api_keys        One credential per external system. Verified by the /integration/**
--                   filter chain; never by a user session and never by a JWT.
--   api_key_usage   One row per integration request — the audit trail the requirement asks
--                   for ("API Key usage should be auditable ... including the client/system
--                   and request time").
--   permissions     Four admin authorities for the key-management page, granted to ADMIN.
--   one index       On log_sheets, for the date-range query the integration polls.
--
-- WHY A SEPARATE CREDENTIAL TABLE RATHER THAN A SERVICE USER
--
-- A service account would inherit the whole user model: a role, unit assignments, a password
-- policy, a login-attempt lock, an api_sessions row, and — worst — the three access layers in
-- docs/security.md, every one of which assumes a human principal. The requirement is the
-- opposite of that: "third-party endpoints must be separate from normal user authentication
-- APIs". A key is not a user, so it is not stored as one.
--
-- THE KEY IS SHOWN ONCE
--
-- Presented format: lsk_<key_id>_<secret>
--   key_id      public, indexed, unique — the lookup column
--   secret      256 bits of SecureRandom, never stored
--   secret_hash SHA-256 of the secret
--
-- Splitting the key into a public id and a secret is what makes verification ONE indexed read
-- plus ONE hash comparison. The alternative — hashing the presented key and scanning — either
-- forces a table scan or makes the hash the primary key, and then an administrator cannot be
-- shown which key a usage row belongs to.
--
-- SHA-256 and not BCrypt, deliberately. A slow KDF exists to make low-entropy passwords
-- expensive to guess. This secret is 256 random bits: there is nothing to guess, and BCrypt's
-- ~100 ms would be paid on every request of an integration that may poll every minute.
-- This is the same reasoning behind GitHub's and Stripe's key formats.
--
-- REVOKE, NEVER DELETE
--
-- The row survives revocation so past api_key_usage rows stay attributable, and so that
-- disabling one integration provably cannot affect another (each key is an independent row;
-- there is no shared state between them).
--
-- DISABLE vs REVOKE — two different admin actions, on purpose:
--   active = false   reversible pause. "Stop this integration until we finish the migration."
--   revoked_at set   permanent. The key can never be re-enabled; a new one must be issued.
-- Both are refused at the same place in the filter, so neither depends on the other.
-- =============================================================================


-- =============================================================================
-- TABLE: api_keys
-- One credential per third-party system.
--
-- Columns:
--   client_name    Identifies the system/client this key belongs to (required, unique
--                  case-insensitively — two keys called "ERP" is how the wrong one gets
--                  revoked). Re-issuing for the same client means revoking and creating,
--                  which is why uniqueness is partial on non-revoked rows only.
--   description    Free-text note: who owns the integration, which ticket asked for it.
--   key_id         Public half of the presented key. The per-request lookup key.
--   secret_hash    SHA-256 (hex) of the secret half. The secret itself is never stored.
--   prefix         First few characters of the presented key, kept so the admin list can
--                  show "lsk_a1b2c3d4…" — enough for a human to match a key against what
--                  the integrator has, and useless to an attacker.
--   active         Reversible enable/disable switch.
--   expires_at     Optional hard expiry (epoch millis). NULL = does not expire.
--   revoked_*      Permanent revocation, with who and why.
--   last_used_at   Throttled touch (see ApiKeyService.LAST_USED_THROTTLE_MS) so a polling
--                  integration does not cause a write per request. Updated with a
--                  @Modifying query, never save(), so it never reaches the audit aspect.
-- =============================================================================
CREATE TABLE api_keys (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name        VARCHAR(255) NOT NULL,
    description        VARCHAR(1000),
    key_id             VARCHAR(64)  NOT NULL,
    secret_hash        VARCHAR(64)  NOT NULL,
    prefix             VARCHAR(32)  NOT NULL,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         BIGINT       NOT NULL,
    created_by_user_id BIGINT,
    expires_at         BIGINT,
    revoked_at         BIGINT,
    revoked_by         BIGINT,
    revoke_reason      VARCHAR(500),
    last_used_at       BIGINT,
    CONSTRAINT uk_api_keys_key_id UNIQUE (key_id),
    CONSTRAINT fk_api_keys_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_api_keys_revoked_by FOREIGN KEY (revoked_by) REFERENCES users (id)
);

-- One live key per client name. Partial on non-revoked rows: revoking and re-issuing for the
-- same client is the normal rotation path and must not collide with the retired row.
CREATE UNIQUE INDEX ux_api_keys_client_name_live
    ON api_keys (LOWER(client_name)) WHERE revoked_at IS NULL;

CREATE INDEX idx_api_keys_revoked_at ON api_keys (revoked_at);


-- =============================================================================
-- TABLE: api_key_usage
-- One row per request that reached the integration chain, including the rejected ones.
--
-- A dedicated table rather than audit_log, for two reasons that both matter:
--   • audit_log records CHANGES to rows. An integration only reads, so every one of these
--     would be a change record for a change that did not happen.
--   • an integration polling every minute writes ~1,400 rows a day. Mixed into audit_log
--     that drowns the record of who edited what, which is the one question that table
--     exists to answer.
--
-- api_key_id is nullable ON PURPOSE: a request presenting an unknown key has no key to point
-- at, and those are precisely the rows an administrator wants to see. key_id and client_name
-- are denormalised so the row still reads correctly after the key row is gone, and so the
-- listing needs no join.
--
-- Written asynchronously on auditExecutor. The response does not wait for it, and its
-- CallerRunsPolicy means a burst degrades to a synchronous insert rather than to a dropped
-- audit row (see AsyncConfig, and gotcha #68).
-- =============================================================================
CREATE TABLE api_key_usage (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id   BIGINT,
    key_id       VARCHAR(64),
    client_name  VARCHAR(255),
    method       VARCHAR(10)  NOT NULL,
    path         VARCHAR(512) NOT NULL,
    query_string VARCHAR(1000),
    status_code  INT          NOT NULL,
    outcome      VARCHAR(32)  NOT NULL,
    result_count INT,
    duration_ms  BIGINT,
    ip_address   VARCHAR(64),
    user_agent   VARCHAR(512),
    requested_at BIGINT       NOT NULL,
    CONSTRAINT fk_api_key_usage_key FOREIGN KEY (api_key_id) REFERENCES api_keys (id)
);

CREATE INDEX idx_api_key_usage_requested_at ON api_key_usage (requested_at);
CREATE INDEX idx_api_key_usage_key_requested ON api_key_usage (api_key_id, requested_at);


-- =============================================================================
-- INDEX: the integration's date-range query
--
-- The read pattern here is the opposite of the rest of the application. A tablet syncs a
-- handful of sheets it owns; an integration asks "everything that finished between these two
-- instants", possibly every minute, and gets back a page of a much larger set.
--
-- The expression matches IntegrationLogSheetRepository's ORDER BY and WHERE exactly, which is
-- what lets PostgreSQL use it for both. It is deliberately NOT partial on status: a partial
-- index's predicate has to be *proved* implied by the query, and PostgreSQL cannot prove that
-- for a bound parameter list — the index would silently never be used.
--
-- Why COALESCE at all: "when did this sheet finish" is a different column per state, and each
-- one is written exactly once, so the fallback chain is unambiguous rather than a guess.
--   SUBMITTED / VOIDED   completed_at  (always set — every completion path writes it)
--   EXPIRED              expired_at
--   CANCELLED            cancelled_at
-- =============================================================================
CREATE INDEX idx_log_sheets_status_finalized_at
    ON log_sheets (status, (COALESCE(completed_at, expired_at, cancelled_at)));


-- =============================================================================
-- PERMISSIONS — the admin page that manages keys
--
-- The integration endpoints themselves get NO permission row. They are not reachable by any
-- role: the /integration/** chain has no user principal at all, so there is nothing for a
-- role to grant. That separation is the requirement, not an omission.
--
-- V1's blanket CROSS JOIN grant to ADMIN was a one-time snapshot and does not cover rows
-- inserted here — see gotcha #22. Every grant below is therefore explicit.
-- =============================================================================
INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
    ('GET:/integration-keys',               'مشاهده کلیدهای یکپارچه‌سازی', 'admin', 'GET',  '/integration-keys'),
    ('POST:/integration-keys',              'ایجاد کلید یکپارچه‌سازی',     'admin', 'POST', '/integration-keys'),
    ('POST:/integration-keys/{id}/status',  'فعال/غیرفعال کردن کلید',      'admin', 'POST', '/integration-keys/{id}/status'),
    ('POST:/integration-keys/{id}/revoke',  'ابطال کلید یکپارچه‌سازی',     'admin', 'POST', '/integration-keys/{id}/revoke');

-- ADMIN only. Issuing a credential that reads every completed round in the plant is an
-- administrative act; HIGH_USER deliberately does not get it.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM roles r CROSS JOIN permissions p
 WHERE r.code = 'ADMIN'
   AND p.code IN ('GET:/integration-keys',
                  'POST:/integration-keys',
                  'POST:/integration-keys/{id}/status',
                  'POST:/integration-keys/{id}/revoke');
