-- =============================================================================
-- V4 — the reading a correction replaced
--
-- WHAT THIS FIXES
--
-- Until now, correcting a reading destroyed the previous one with no trace anywhere on the
-- server. `applyWebEntryValues` and `mergeMobileEntryUpdates` both call `setFormData(values)`
-- and save; the only things that move with it are `entry_source`, `filled_by_user_id` and
-- `updated_at`. So after a supervisor reopens a submitted round and edits an entry, the row
-- says "the value is X and the supervisor recorded it" — and what the operator actually
-- measured in front of the equipment is gone.
--
-- It is not covered by the generic audit trail either, and could not be: `LogSheetEntry` is in
-- `AuditEntitySupport.EXCLUDED_TYPES`, and even if it were not, `auditFields()` skips every
-- Map/Collection field, so `form_data` would never appear in a diff. Auditing the entity is
-- also the wrong shape — a mobile submit saves every entry of the sheet (up to 300) on every
-- push, which is the volume problem that put `ImportJob` on that exclusion list in the first
-- place.
--
-- Everything else in this system goes out of its way not to lose a reading:
-- `log_sheet_void_submissions` keeps a whole payload the server refused, and the tablet keeps
-- `logSheetUserArchives` per user. A supervisor's correction was the one path where a real
-- field measurement disappeared silently. This table closes it.
--
-- WHAT IS STORED, AND WHY IT IS THE **OLD** VALUE
--
-- One row per genuine overwrite, holding the value that was **replaced**. The current value is
-- always in `log_sheet_entries`, so storing the new one as well would duplicate it on every
-- correction; with this shape the full history of an entry is
--
--     [revision 1 .. revision n]  ++  [log_sheet_entries.form_data]
--
-- with no duplication and no ambiguity about which end is current. It is the same reasoning as
-- `asset_status_change_requests.applied_old_status`: what a change actually replaced is the
-- value worth keeping, because it is the only one that cannot be read anywhere else.
--
-- A consequence worth stating: **filling an empty entry writes no row.** Nothing was replaced.
-- A normal round therefore produces zero revisions, and the table stays proportional to the
-- number of corrections rather than to the number of readings.
-- =============================================================================

CREATE TABLE log_sheet_entry_revisions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- CASCADE from both parents. A revision is part of the sheet's record, not an independent
    -- fact about the plant: when a log sheet is deleted the readings go with it, and a history
    -- of values whose entry no longer exists could never be rendered.
    log_sheet_entry_id    BIGINT NOT NULL REFERENCES log_sheet_entries(id) ON DELETE CASCADE,
    log_sheet_id          BIGINT NOT NULL REFERENCES log_sheets(id)        ON DELETE CASCADE,

    -- Denormalised so the per-asset history can be read without joining back through the entry,
    -- and so it survives as a readable record if the asset is ever renamed. RESTRICT, like every
    -- other reference to an asset in this schema.
    asset_id              BIGINT REFERENCES asset_entries(id) ON DELETE RESTRICT,

    -- The value this change replaced, in exactly the shape `log_sheet_entries.form_data` had —
    -- keys the sheet's frozen snapshot defines, and only the ones that were actually answered.
    form_data             JSONB NOT NULL,

    -- Carried with the value rather than recomputed later: the bands that produced this severity
    -- were the ones frozen on the sheet at the time, and re-evaluating a historical value against
    -- today's definitions is precisely what `field_definitions_snapshot` exists to prevent.
    max_severity          VARCHAR(10),
    breached_fields       JSONB,

    -- How the replaced value was captured, and by whom, and when the operator recorded it on
    -- the device. `recorded_at` is the entry's own `updated_at` — device time — so a history
    -- line says when somebody was standing at the equipment, not when a supervisor got to it.
    entry_source          VARCHAR(20),
    recorded_by_user_id   BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    recorded_at           BIGINT,

    -- Who overwrote it and when the server accepted that. Server time, deliberately: this is a
    -- fact about the correction, not about a measurement, and a device clock has no authority
    -- over it.
    superseded_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    superseded_at         BIGINT NOT NULL,
    superseded_source     VARCHAR(20),

    -- The sheet's status as the service saw it when the value was replaced. Context for the
    -- reader, not a discriminator to branch on — a supervisor's correction after a reopen and a
    -- second operator redoing an asset mid-round both happen at IN_PROGRESS, and what actually
    -- tells them apart is `superseded_by_user_id` next to the sheet's action log. Kept as a
    -- plain string, like `max_severity`, so a future status cannot break reads of historic rows.
    sheet_status          VARCHAR(30),

    CONSTRAINT ck_lser_max_severity
        CHECK (max_severity IS NULL OR max_severity IN ('OK','WARNING','DANGER')),
    CONSTRAINT ck_lser_entry_source
        CHECK (entry_source IS NULL OR entry_source IN ('WEB','PWA_NFC','PWA_MANUAL')),
    CONSTRAINT ck_lser_superseded_source
        CHECK (superseded_source IS NULL OR superseded_source IN ('WEB','MOBILE','SERVER'))
);

-- The render query: one entry's history, oldest first. `id DESC` on the index and an ORDER BY
-- either way both use it; the identity column is monotonic within a table, so it orders the
-- revisions of one entry correctly without depending on a timestamp that two paths could write
-- out of order.
CREATE INDEX idx_lser_entry ON log_sheet_entry_revisions (log_sheet_entry_id, id DESC);

-- The detail page loads every revision for a sheet in one query rather than one per asset —
-- the same batch-map pattern the rest of the panel uses.
CREATE INDEX idx_lser_sheet ON log_sheet_entry_revisions (log_sheet_id);

COMMENT ON TABLE log_sheet_entry_revisions IS
    'Append-only history of log-sheet entry values. One row per overwrite of a non-empty '
    'form_data, holding the value that was REPLACED; the current value lives in '
    'log_sheet_entries. Filling an empty entry writes no row.';
