-- =============================================================================
-- V4 — entry revisions, progress sync, and supervisor approval
--
-- Three features that ship together, consolidated into ONE migration so an operational database
-- advances by a single version for changes it has never seen.
--
-- THE RULE BEHIND THAT, restated because it is the one that keeps this directory safe:
-- a migration that has never reached an operational database is still editable; one that has is
-- not. V1, V2 and V3 are closed. This file is closed from the moment it is deployed. Production
-- has run up to V3, so what were developed as V4, V5 and V6 while unreleased are the three
-- sections below.
--
-- WHAT IS IN HERE, in the order it appears:
--
--   1. `log_sheet_entry_revisions` — the reading a correction replaced. Until now a supervisor
--      editing a submitted round destroyed the operator's measurement with no trace anywhere on
--      the server, and the generic audit trail could not cover it.
--   2. Progress sync — a round being walked becomes visible before it is finished:
--      `log_sheets.draft_saved_by_user_id` / `draft_source`, the
--      `POST:/api/log-sheets/progress` permission, and the index behind "N of M assets recorded".
--   3. Approval and two review queues — `log_sheets.approved_at` / `approved_by_user_id` with
--      their two permissions, `log_sheet_entry_revisions.attachment_snapshot` (what a deleted
--      attachment *was*), and the ordering index the NFC fault queue needs now that it pages.
--
-- ORDERING MATTERS IN ONE PLACE: section 3 alters `log_sheet_entry_revisions`, which section 1
-- creates. Sections 2 and 3 both INSERT into `permissions` and then grant from an existing
-- permission, so each is self-contained and their relative order does not matter.
--
-- Each section keeps its own original header; nothing below has been rewritten, only joined and
-- renumbered — a file called V4 cannot contain a section that introduces itself as "V6".
-- =============================================================================


-- =============================================================================
-- SECTION 1 — the reading a correction replaced
--
-- WHAT THIS FIXES
--
-- Until now, correcting a reading destroyed the previous one with no trace anywhere on the
-- server. `applyWebEntryValues` and `mergeMobileEntryUpdates` both call `setFormData(values)`
-- and save; the only things that move with it are `entry_source`, `filled_by_user_id` and
-- `updated_at`. So after a supervisor reopens a submitted round and edits an entry, the row
-- says "the value is X and the supervisor recorded it" — and what the operator actually
-- measured in front of the equipment is gone.
--
-- It is not covered by the generic audit trail either, and could not be: `LogSheetEntry` is in
-- `AuditEntitySupport.EXCLUDED_TYPES`, and even if it were not, `auditFields()` skips every
-- Map/Collection field, so `form_data` would never appear in a diff. Auditing the entity is
-- also the wrong shape — a mobile submit saves every entry of the sheet (up to 300) on every
-- push, which is the volume problem that put `ImportJob` on that exclusion list in the first
-- place.
--
-- Everything else in this system goes out of its way not to lose a reading:
-- `log_sheet_void_submissions` keeps a whole payload the server refused, and the tablet keeps
-- `logSheetUserArchives` per user. A supervisor's correction was the one path where a real
-- field measurement disappeared silently. This table closes it.
--
-- WHAT IS STORED, AND WHY IT IS THE **OLD** VALUE
--
-- One row per genuine overwrite, holding the value that was **replaced**. The current value is
-- always in `log_sheet_entries`, so storing the new one as well would duplicate it on every
-- correction; with this shape the full history of an entry is
--
--     [revision 1 .. revision n]  ++  [log_sheet_entries.form_data]
--
-- with no duplication and no ambiguity about which end is current. It is the same reasoning as
-- `asset_status_change_requests.applied_old_status`: what a change actually replaced is the
-- value worth keeping, because it is the only one that cannot be read anywhere else.
--
-- A consequence worth stating: **filling an empty entry writes no row.** Nothing was replaced.
-- A normal round therefore produces zero revisions, and the table stays proportional to the
-- number of corrections rather than to the number of readings.
-- =============================================================================

CREATE TABLE log_sheet_entry_revisions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- CASCADE from both parents. A revision is part of the sheet's record, not an independent
    -- fact about the plant: when a log sheet is deleted the readings go with it, and a history
    -- of values whose entry no longer exists could never be rendered.
    log_sheet_entry_id    BIGINT NOT NULL REFERENCES log_sheet_entries(id) ON DELETE CASCADE,
    log_sheet_id          BIGINT NOT NULL REFERENCES log_sheets(id)        ON DELETE CASCADE,

    -- Denormalised so the per-asset history can be read without joining back through the entry,
    -- and so it survives as a readable record if the asset is ever renamed. RESTRICT, like every
    -- other reference to an asset in this schema.
    asset_id              BIGINT REFERENCES asset_entries(id) ON DELETE RESTRICT,

    -- The value this change replaced, in exactly the shape `log_sheet_entries.form_data` had —
    -- keys the sheet's frozen snapshot defines, and only the ones that were actually answered.
    form_data             JSONB NOT NULL,

    -- Carried with the value rather than recomputed later: the bands that produced this severity
    -- were the ones frozen on the sheet at the time, and re-evaluating a historical value against
    -- today's definitions is precisely what `field_definitions_snapshot` exists to prevent.
    max_severity          VARCHAR(10),
    breached_fields       JSONB,

    -- How the replaced value was captured, and by whom, and when the operator recorded it on
    -- the device. `recorded_at` is the entry's own `updated_at` — device time — so a history
    -- line says when somebody was standing at the equipment, not when a supervisor got to it.
    entry_source          VARCHAR(20),
    recorded_by_user_id   BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    recorded_at           BIGINT,

    -- Who overwrote it and when the server accepted that. Server time, deliberately: this is a
    -- fact about the correction, not about a measurement, and a device clock has no authority
    -- over it.
    superseded_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    superseded_at         BIGINT NOT NULL,
    superseded_source     VARCHAR(20),

    -- The sheet's status as the service saw it when the value was replaced. Context for the
    -- reader, not a discriminator to branch on — a supervisor's correction after a reopen and a
    -- second operator redoing an asset mid-round both happen at IN_PROGRESS, and what actually
    -- tells them apart is `superseded_by_user_id` next to the sheet's action log. Kept as a
    -- plain string, like `max_severity`, so a future status cannot break reads of historic rows.
    sheet_status          VARCHAR(30),

    CONSTRAINT ck_lser_max_severity
        CHECK (max_severity IS NULL OR max_severity IN ('OK','WARNING','DANGER')),
    CONSTRAINT ck_lser_entry_source
        CHECK (entry_source IS NULL OR entry_source IN ('WEB','PWA_NFC','PWA_MANUAL')),
    CONSTRAINT ck_lser_superseded_source
        CHECK (superseded_source IS NULL OR superseded_source IN ('WEB','MOBILE','SERVER'))
);

-- The render query: one entry's history, oldest first. `id DESC` on the index and an ORDER BY
-- either way both use it; the identity column is monotonic within a table, so it orders the
-- revisions of one entry correctly without depending on a timestamp that two paths could write
-- out of order.
CREATE INDEX idx_lser_entry ON log_sheet_entry_revisions (log_sheet_entry_id, id DESC);

-- The detail page loads every revision for a sheet in one query rather than one per asset —
-- the same batch-map pattern the rest of the panel uses.
CREATE INDEX idx_lser_sheet ON log_sheet_entry_revisions (log_sheet_id);

COMMENT ON TABLE log_sheet_entry_revisions IS
    'Append-only history of log-sheet entry values. One row per overwrite of a non-empty '
    'form_data, holding the value that was REPLACED; the current value lives in '
    'log_sheet_entries. Filling an empty entry writes no row.';


-- =============================================================================
-- SECTION 2 — a round in progress becomes visible before it is finished
--
-- THE GAP THIS CLOSES
--
-- A tablet pushes completions and nothing else. `draft_saved_at` exists but only
-- `saveDraftFromWeb` ever wrote it, so a round being walked in the field was invisible to the
-- server for its whole duration: an operator could fill twenty assets in the first hour, be
-- online the entire time, and a supervisor looking at the sheet would see PENDING or
-- IN_PROGRESS with no data at all. If the sheet then changed hands, the second operator started
-- from an empty form and re-walked ground that had already been covered.
--
-- Worth stating because it makes the asymmetry obvious: **the photographs were already
-- arriving.** Attachments upload as soon as they are captured (`getPendingAttachments` waits
-- for a `logSheetServerId`, which a server-generated sheet always has), so the server held a
-- half-finished round's media and none of its numbers.
--
-- WHAT IS ADDED HERE
--
--   1. `log_sheets.draft_saved_by_user_id` / `draft_source` — who last saved partial values and
--      from which surface. `draft_saved_at` keeps its meaning and its column; it now has two
--      writers instead of one.
--   2. `POST:/api/log-sheets/progress` — the mobile progress endpoint, granted to every role
--      that already holds `POST:/api/log-sheets/batch`, including roles an administrator
--      duplicated.
--   3. A partial index behind the "N of M assets recorded" column.
--
-- WHAT IS NOT ADDED, DELIBERATELY
--
-- No new table for the values. Progress is written straight into `log_sheet_entries` through
-- the same merge the mobile submit uses, for three reasons that a separate per-assignee draft
-- table cannot answer:
--
--   * The handover this system actually performs — operator 1, then operator 2, then the
--     supervisor — requires operator 1's partial work to *be* operator 2's starting point. A
--     side table would have to be promoted into the entries anyway.
--   * Every rule that governs a partial write already exists and is hard-won: `storableFormData`,
--     `wouldBlankUnseenAnswer`, `EntrySeverityEvaluator`, and the `formDataChanged` gate that
--     decides authorship. A second copy of those is how they drift apart.
--   * It changes no report. Every entry-level reporting query filters
--     `log_sheets.status = 'SUBMITTED'` — the two overview counters, the manual-entry split, the
--     silent-asset scan, both exception queries and both asset-parameter queries — and the
--     integration API only ever exposes finished sheets. Verified query by query before writing
--     this file.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Who saved the partial values, and from where
-- -----------------------------------------------------------------------------

-- The account whose save produced the current `draft_saved_at`. Nullable: rows that predate
-- this column have a timestamp and no attribution, and there is nothing to recover for them.
ALTER TABLE log_sheets ADD COLUMN draft_saved_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT;

-- WEB (the panel's «ذخیره پیش‌نویس») or MOBILE (a tablet's progress push).
--
-- This exists so the two can never be confused by a later change. The expiry scheduler used to
-- branch on `draft_saved_at IS NOT NULL` and auto-submit the round; that branch is removed in
-- this release, but if a site ever wants it back it must come back for web drafts only — a
-- mobile round that has merely reported its progress has not been "saved for later" by anyone,
-- and auto-submitting it at the deadline would finalise a round the operator is still walking.
ALTER TABLE log_sheets ADD COLUMN draft_source VARCHAR(20);

ALTER TABLE log_sheets ADD CONSTRAINT ck_log_sheets_draft_source
    CHECK (draft_source IS NULL OR draft_source IN ('WEB','MOBILE'));

-- Every draft that exists today came from the web panel — it was the only writer.
UPDATE log_sheets SET draft_source = 'WEB' WHERE draft_saved_at IS NOT NULL AND draft_source IS NULL;

COMMENT ON COLUMN log_sheets.draft_saved_at IS
    'Last time partial values were stored on this sheet without a submission, from either '
    'surface. See draft_source for which one.';


-- -----------------------------------------------------------------------------
-- 2. The progress endpoint's permission
-- -----------------------------------------------------------------------------

INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
('POST:/api/log-sheets/progress', 'API — ثبت پیشرفت لاگ‌شیت (پیش‌نویس)', 'api', 'POST', '/api/log-sheets/progress');

-- Granted to whoever may already deliver a round from a tablet.
--
-- Derived from the existing grant rather than written as a list of the five system role codes,
-- and that is deliberate: an administrator who duplicated OPERATOR gets a role with a NEW code
-- and the same permissions, and a hard-coded list would leave that copy unable to report
-- progress while still able to submit — the exact class of breakage capabilities were
-- introduced to end. V1's blanket CROSS JOIN grant was a one-time snapshot and does not cover
-- rows inserted here, so ADMIN and HIGH_USER are reached through the same rule.
INSERT INTO role_permissions (role_id, permission_id)
SELECT rp.role_id, progress.id
FROM role_permissions rp
JOIN permissions batch    ON batch.id = rp.permission_id AND batch.code = 'POST:/api/log-sheets/batch'
CROSS JOIN permissions progress
WHERE progress.code = 'POST:/api/log-sheets/progress'
ON CONFLICT (role_id, permission_id) DO NOTHING;


-- -----------------------------------------------------------------------------
-- 3. "N of M assets recorded"
-- -----------------------------------------------------------------------------

-- The log-sheet list and the sheet's own page both show how far a round has got, counted as
-- entries that carry a reading. `max_severity IS NOT NULL` is the exact test for that — the
-- evaluator nulls it when form_data holds no answer and always writes at least 'OK' when it
-- does — and this is the third partial index built on that predicate, alongside
-- idx_log_sheet_entries_asset_read and idx_log_sheet_entries_breaches.
--
-- Partial rather than plain: the count is asked for one page of sheets at a time, and the rows
-- that matter are the filled minority. The existing idx_log_sheet_entries_log_sheet_id still
-- serves the denominator.
CREATE INDEX idx_log_sheet_entries_filled ON log_sheet_entries (log_sheet_id)
    WHERE max_severity IS NOT NULL;


-- =============================================================================
-- SECTION 3 — a supervisor's approval, a deadline change that says what it changed,
--      and the metadata of an attachment a correction removed
--
-- Four unrelated changes in one file because they ship together. Each keeps its own header.
-- =============================================================================


-- #############################################################################
-- SECTION 3.1 — approval
-- #############################################################################
--
-- A completed round now has one more step: a supervisor reads it and accepts it. The status
-- reaches APPROVED from SUBMITTED and returns only to SUBMITTED; nothing else touches it.
--
-- WHY THIS IS A STATUS AND NOT A FLAG
--
-- It is a lifecycle state, and this schema already models lifecycle in `status` with a companion
-- timestamp per transition (claimed_at, started_at, completed_at, expired_at, cancelled_at). A
-- nullable `approved_at` alone would have been cheaper — no condition anywhere would have needed
-- touching — but it would also have left the question "what does status=VOIDED with approved_at
-- set mean?" permanently open, and every future reader would have to reconstruct the answer.
--
-- THE COST, AND HOW IT IS PAID
--
-- Adding a status means every condition that asks "was this round completed" has to accept both
-- values. There are about forty of them and **a missed one is silent** — no error, just a smaller
-- number in a report about a plant. So the rule is mechanical rather than remembered:
-- `LogSheetStatus.COMPLETED_STATUSES` is the only way to ask, and
-- `CompletedStatusConditionTest` fails the build for anything that names SUBMITTED alone outside
-- a short allow-list of transition guards.
--
-- NO BACKFILL, DELIBERATELY
--
-- Every existing SUBMITTED sheet stays SUBMITTED. Nobody approved them, and stamping an approval
-- nobody performed would be inventing a review. Expect the "awaiting approval" figure to be large
-- on the first day; that number is true.

ALTER TABLE log_sheets ADD COLUMN approved_at         BIGINT;
ALTER TABLE log_sheets ADD COLUMN approved_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT;

COMMENT ON COLUMN log_sheets.approved_at IS
    'When a supervisor accepted this completed round. Set with status = APPROVED and cleared '
    'when the approval is withdrawn. The approver may be the same person who completed it.';

-- The two endpoints. Their own permission rows because approving is a distinct authority from
-- voiding even though the same people usually hold both — a site that wants a separate reviewer
-- role needs to be able to say so.
INSERT INTO permissions (code, name, category, http_method, endpoint_path) VALUES
('POST:/log-sheets/{id}/approve',   'تأیید لاگ‌شیت',      'log-sheet', 'POST', '/log-sheets/{id}/approve'),
('POST:/log-sheets/{id}/unapprove', 'لغو تأیید لاگ‌شیت', 'log-sheet', 'POST', '/log-sheets/{id}/unapprove');

-- Granted to whoever may already void a completed round — the same supervisory judgement.
--
-- Derived from the existing grant rather than written as a list of system role codes, for the
-- reason section 2 records: an administrator's duplicated role has a NEW code and the same permissions,
-- and a hard-coded list would leave that copy able to void a round and unable to approve one.
-- V1's blanket CROSS JOIN grant was a one-time snapshot and does not cover rows inserted here, so
-- ADMIN and HIGH_USER are reached through the same rule.
INSERT INTO role_permissions (role_id, permission_id)
SELECT rp.role_id, p.id
FROM role_permissions rp
JOIN permissions v ON v.id = rp.permission_id AND v.code = 'POST:/log-sheets/{id}/void'
CROSS JOIN permissions p
WHERE p.code IN ('POST:/log-sheets/{id}/approve', 'POST:/log-sheets/{id}/unapprove')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- "Completed but not yet reviewed" is the supervisor's queue, and it is a small slice of a table
-- that grows with every round ever run. Partial so the index stays proportional to the backlog
-- rather than to the history.
CREATE INDEX idx_log_sheets_awaiting_approval ON log_sheets (operational_unit_id, completed_at)
    WHERE status = 'SUBMITTED';


-- #############################################################################
-- SECTION 3.2 — what an attachment was, after it is gone
-- #############################################################################
--
-- `log_sheet_entry_revisions` (section 1) keeps the reading a correction replaced. When that reading was
-- a photo or a voice note, the row holds the attachment's **id** — and `AttachmentService.delete`
-- removes the row and the file outright, so the id resolves to nothing and the history panel can
-- only say «فایل پیوست در دسترس نیست».
--
-- That is honest but useless: it cannot distinguish "a photo was deleted here" from "the file is
-- missing from storage", and it says nothing about what the deleted evidence was.
--
-- This column carries the metadata forward: for each attachment id referenced by the superseded
-- value, its kind, mime type, size, duration and who captured it when. The bytes are still gone —
-- keeping those is a soft-delete design with a disk-retention story behind it, deliberately not
-- taken on here — but the record can now say "a 20-second voice note recorded by X at 08:15 was
-- removed", which is what a reviewer actually needs to know.

ALTER TABLE log_sheet_entry_revisions ADD COLUMN attachment_snapshot JSONB;

COMMENT ON COLUMN log_sheet_entry_revisions.attachment_snapshot IS
    'Metadata for each attachment the superseded value referenced, keyed by attachment id: '
    'kind, mimeType, sizeBytes, durationMs, width, height, uploadedAt, createdByUserId. Written '
    'at revision time because the rows it describes may be deleted afterwards. Null when the '
    'superseded value referenced no attachments.';


-- #############################################################################
-- SECTION 3.3 — pagination for the two review queues
-- #############################################################################
--
-- `/nfc-fault-reports` loaded every row ever filed and rendered them all. It grows without bound
-- in normal use — one row per broken chip, nothing ever deletes them — and it is read most on the
-- days it is longest. It now filters and pages in SQL, which needs its ordering indexed or the
-- database sorts the whole table to produce twenty-five rows.
--
-- Both columns, in the query's own order. `created_at` is the reporting clock and repeats freely
-- (a phone syncing a backlog files several reports in the same millisecond), so the queue breaks
-- ties on the id — and an index on `created_at` alone would leave the database re-sorting each
-- group of ties, which is exactly the boundary a page break can fall inside.

CREATE INDEX idx_nfc_fault_reports_created_at ON nfc_fault_reports (created_at DESC, id DESC);

-- `/asset-status-requests` was already paged and filtered in SQL, and orders by `id DESC` — the
-- primary key's own index serves that, so it needs nothing here. Its defect was in the pager:
-- `fragments/list-toolbar :: pagination` built links from a hard-coded list of parameter names
-- and dropped every filter called anything else, so page two of a filtered list was page two of
-- the unfiltered one. Fixed in `ListFilterAdvice`, which is not a schema change.
